### ISSUE TITLE
Change color of as of based on selection

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#1008]
As discussed in call we need to show prominence of filters when applied on Canonizer. So for that as suggestion we can change color of texts Or we can change background color of filter when applied by user. 

@shahab-ramzan We might need discussion or some sort of demo before implementation.

**Comment by rupalichavan9860** [comment]
Not implemented on staging

**Comment by rupalichavan9860** [comment]
Functionality is implemented on staging and logging issues separately

**Comment by rupalichavan9860** [comment]
Functionality is implemented on live and logging issues separately
