### ISSUE TITLE
Change the order of sections on mobile screen

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#1009]
As discussed in agenda meeting we need to change order of sections for mobile screen on topic detail page. So this was the order discussed. 

1- Camp Sort Tree
2- Statement
3- Support Tree
4- Topic Record
5- Camp Record

Then news feed and then recent activities.

**Comment by hassaanCD** [comment]
@rupalichavan9860  Can you please verify this order of topic detail page ?

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by rupalichavan9860** [comment]
Working fine on live
