### ISSUE TITLE
On Cancel any Change , It should popup confirmation

### ISSUE THREAD

**Issue by sajid315** [the-canonizer/canonizer-3.0-frontend#1020]
On cancel it should confirm by user as yes/no confirmation.
![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/111273633/eccbfcad-4b09-42f4-838b-46e38c029548)

**Comment by hassaanCD** [comment]
Verified on staging



![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/f5d33005-cb9c-4f86-bc53-e3cbdd88e220)

**Comment by rupalichavan9860** [comment]
Verified on live
