### ISSUE TITLE
Emails : We have to replace the forward slash (/) with arrow (>) in all the breadcrumbs throughout the application

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer-3.0-frontend#1040]
Reference ticket : https://github.com/the-canonizer/canonizer-3.0-frontend/issues/975

Implement the same for emails

**Comment by ks-rahul** [comment]
@rupalichavan9860 I can't find the namespace name mentioned anywhere in the email. Do you know of any specific email that includes the namespace name

**Comment by ashish76** [comment]
@rupalichavan9860 could you please share the email where the namespace is mentioned?

**Comment by rupalichavan9860** [comment]
@ashish76 @ks-rahul Please refer below screenshot : 
![image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/40416610/4d7e2447-f0bc-4d27-a5ad-470d0c2f1b3c)

**Comment by rupalichavan9860** [comment]
Not fixed

**Comment by ashish76** [comment]
@rupalichavan9860 Could you please check once again? The queue was not restarted on staging, but it is currently functioning properly.

**Comment by rupalichavan9860** [comment]
@ashish76 I can see it(>), but if you check the application, there are two, yet there is just one in the emails.

Refer screenshots : 
Application : 
![image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/40416610/0140fc66-ed98-4968-b8ed-1c3cd464277a)


Emails : 
![image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/40416610/bbc1c036-4019-4c47-b693-fbe60939e0fc)

**Comment by rupalichavan9860** [comment]
@ashish76 Please check below screenshot : 
![image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/40416610/2d0c5eed-2482-4753-9e31-45d2fb7b74ac)

**Comment by ashish76** [comment]
Noted @rupalichavan9860 I will rectify this as well

**Comment by ashish76** [comment]
@rupalichavan9860 the code has not been deployed and that is why it is showing like this. Once it is deployed then you can check this.

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on live
