### ISSUE TITLE
[object Object] showing as default text in Edit Summary field for camp statement

### ISSUE THREAD

**Issue by mark-shamy** [the-canonizer/canonizer-3.0-frontend#1059]

**Comment by ashish76** [comment]
Hi, @mark-shamy we are unable to reproduce the issue described in the title. Could you please check again and let us know if there are any specific cases or steps?

**Comment by mark-shamy** [comment]
Will create recreation steps

**Comment by cd-ali-ehsan** [comment]
Duplicate of https://github.com/the-canonizer/canonizer-3.0-frontend/issues/928

**Comment by rupalichavan9860** [comment]
Verified on live
