### ISSUE TITLE
Rename to Consensus Tree

### ISSUE THREAD

**Issue by CanonizerJim** [the-canonizer/canonizer-3.0-frontend#1071]
Relabel the Canonizer Sorted Camp Tree to Consensus Tree. Also look through supporting materials including help files, emails, and in source code and replace references to Canonizer Sorted Camp Tree to Consensus Tree.

**Comment by sajid315** [comment]
@shahab-ramzan I verified the above mentioned label from back-end, including code files, email templates. So only need to update it from front end UI.

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by rupalichavan9860** [comment]
Verified on live
