### ISSUE TITLE
"As of Date" filter cross button issue

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#1077]
When user click on "cross" button then instead of closing calendar, it is opening calendar again. As shown in attached image below:

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/f9e127a2-8db7-4389-b5c4-2ed66c8bfb7a)

**Comment by shahab-ramzan** [comment]
@rupalichavan9860  @hassaanCD   Currently cross button is setting date to default(current date) and date picker remains open. Do you want us to change it's behavior to set date to default and close the date picker?

**Comment by rupalichavan9860** [comment]
@shahab-ramzan I am fine with current behavior . If necessary, we can discuss in a meeting with Brent and others.

**Comment by shahab-ramzan** [comment]
@rupalichavan9860 It's not necessary to discuss because cross button is for resetting the selected data not for closing the calendar. I'm updating the status of this ticket.

**Comment by rupalichavan9860** [comment]
Working fine

**Comment by rupalichavan9860** [comment]
Working fine on live
