### ISSUE TITLE
Algorithm Preference change issue

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#1087]
When user choose default "Algorithm preference" in "Account Settings", it is not effecting in Canonizer.

![Image](https://user-images.githubusercontent.com/120023458/244024715-99af2b18-8ba8-451a-b395-af5a10d826d9.png)

![Image](https://user-images.githubusercontent.com/120023458/244024758-2fa0654e-07c4-4d7c-9abe-7c24bc923c3e.png)

**Comment by rupalichavan9860** [comment]
@hassaanCD It's not an issue. Clear your cache whenever you update your profile (change your Algorithm Preference ), otherwise it will automatically display the cached algorithm.

**Comment by sajid315** [comment]
From back-end its returning a key in profile as "default_algo", but on front-end its not updating. Needed to fixed from front-end.

**Comment by hassaanCD** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on live
