### ISSUE TITLE
Frontend placement issue

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#1100]

**Comment by hassaanCD** [comment]
- "Only My Topic" checkbox must be with "Search Topic Name" field
- "Sorting" must be with "Select Canon"



![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/22d3c370-cfea-47cc-a053-dd41fb397312)

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by hassaanCD** [comment]
Wor
