### ISSUE TITLE
Update AsOfDate for statement and camp record API

### ISSUE THREAD

**Issue by sajid315** [the-canonizer/canonizer-3.0-frontend#1102]
Following api's needed to be updated in case of payload.

1. Get camp statement and get camp record.
2. Payload must be consist on Unix timestamp. 
3. Compare the payload as_of_date with get API.

**Comment by sajid315** [comment]
@shahab-ramzan As per discussion of me with @rupalichavan9860 , 
We faced the issue on staging before release to production so we reverted back our changes in following PR, then release is done by Ashutosh.
https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1122

And now we have to append only date in case of previous as of date. So Wahaj working on it.

**Comment by DevAlchemyCD** [comment]
yes it's done in following PR https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1127
