### ISSUE TITLE
Camp Tree layout changes on topic detail page

### ISSUE THREAD

**Issue by ks-rahul** [the-canonizer/canonizer-3.0-frontend#1145]
https://xd.adobe.com/view/ed21cbe6-addc-4eb6-98a7-e9066d40b19e-b872/?fullscreen

**Comment by mark-shamy** [comment]
"Canonizer Sorted Camp Tree" must be named "Consensus Tree"

**Comment by rupalichavan9860** [comment]
Functionality has been implemented. We are keeping track of issues separately.

**Comment by rupalichavan9860** [comment]
Verified on live
