### ISSUE TITLE
Algorithms are not listing on staging site

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#1147]
As shown in attached screenshot below:

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/dc544c6a-5975-4a6e-bad5-7488073a22cb)

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by hassaanCD** [comment]
Working fine on live
