### ISSUE TITLE
Enhancing Google Lighthouse Report for Improved Website Performance

### ISSUE THREAD

**Issue by akuks** [the-canonizer/canonizer-3.0-frontend#1152]
Mark noticed issue in the Google Lighthouse report.

We need to work  to enhance the performance of our website by optimising it based on the recommendations provided by Google Lighthouse. Google Lighthouse is a powerful tool that analyses web pages and provides valuable insights and suggestions to improve various performance aspects.

- Performance
- Accessibility
- Best Practices
- SEO

**Comment by shahab-ramzan** [comment]
Progress In this task

- Configured next-build-analyzer 
- Configured a package (yarn run next-unused) to identify unused files (Unused files are listed below)
- Configured a package (npx npm-check) to identify the unused packages (unused packages are listed below)
- Identified multiple Rich Text Editors (ckEditor and react-quill) are being used at the same time (discussed in the call and created github issue)

**Unused Files:**  @ks-rahul  @vikasranatalentelgia Please mark the files that we need to keep. 

- [ ] - src/assets/fonticons/demo-files/demo.js
- [ ] - src/components/ComponentPages/ArchivedCampCheckBox/archivedCampCheckBox.test.tsx
- [ ] - src/components/ComponentPages/CompareStatement/types.d.ts
- [x] - src/components/ComponentPages/RemovedSupportList/UI/TopicSubscriptionsTab.tsx
- [x] - src/components/ComponentPages/RemovedSupportList/UI/index.tsx
- [x] - src/components/ComponentPages/RemovedSupportList/index.tsx
- [ ] - src/components/ComponentPages/SettingsUI/test/settings.test.tsx
- [ ] - src/components/ComponentPages/UserProfile/_test_/userProfile.test.tsx
- [ ] - src/components/common/ArchivedCampMsg/archiveCampMsg.test.tsx
- [ ] - src/components/common/FormatDate/formatDate.test.tsx
- [x] - src/components/common/editor/index.tsx
- [ ] - src/components/libraries/likeFreshChat.ts
- [ ] - src/firebaseConfig/gtag.ts
- [ ] - src/firebaseConfig/scripts.tsx
- [ ] - src/network/api/footerSocialLinksApi.ts
- [ ] - src/network/request/footerRequests.ts
- [ ] - src/utils/history.ts
- [x] - src/utils/testUtils.tsx

**Unused Packages:** 


- [x] @babel/core
- [x] - crypto-js
- [x] - json2mq
- [x] - next-global-css
- [x] - next-plugin-antd-less
- [x] - next-useragent
- [x] - pm2
- [x] - react-horizontal-timeline
- [x] - react-player
- [x] - react-redux-toastr
- [x] - redux-logger
- [x] - redux-thunk
- [x] - video.js
- [x] - draftjs-to-html
