### ISSUE TITLE
Option to "Open Link in new tab" on right click on nick name on support tree on topic page

### ISSUE THREAD

**Issue by rohit-talentelgia** [the-canonizer/canonizer-3.0-frontend#1157]
![image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/8575740/484a7c76-4bad-4a02-9382-db077f63ffa5)

As a user, I should be able to right-click on nick name to open the page in a new tab.

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by rupalichavan9860** [comment]
Working fine on live
