### ISSUE TITLE
Make tree drawer as a part of topic detail page's URL

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#1168]
**Points to cover in this Ticket** 
- By default tree drawer should be closed 
- When user comes from Home or Browse page Drawer should be opened
- When user shares URL with someone else or opens it in new tab open the tree drawer according to the URL parameter of drawer

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by rupalichavan9860** [comment]
Verified on live
