### ISSUE TITLE
Layout changes for topic details page.

### ISSUE THREAD

**Issue by ks-rahul** [the-canonizer/canonizer-3.0-frontend#1185]
https://github.com/the-canonizer/canonizer-3.0-frontend/issues/1175

**Comment by ks-rahul** [comment]
![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/95217406/949a44e4-b838-4142-95eb-4dcaa31b2a15)

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by rupalichavan9860** [comment]
Verified on live
