### ISSUE TITLE
Remove Create New Camp Button

### ISSUE THREAD

**Issue by mark-shamy** [the-canonizer/canonizer-3.0-frontend#1187]
Remove Create New Camp button from the left mini side bar on the Topic page. Camp creation using this button is confusing and is adding visual noise. When a user creates a camp this way they must specify the parent using a flat drop-down list. Camps ideally should only be created from within the consensus tree.

**Comment by ashish76** [comment]
Hi @mark-shamy 

The "Create New Camp" button from the left mini side (navigation drawer) has been removed and deployed on the staging. Just to validate the implementation of what you specified in the description, please see the attached screenshot. Please let me know if any changes to be done. Thanks 

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/23633446/1fc6f6d8-9e94-40cc-8af1-b90c1fdfeccb)

**Comment by rupalichavan9860** [comment]
This is working fine on live as per requirement so closing this ticket
