### ISSUE TITLE
Move Create New Topic

### ISSUE THREAD

**Issue by mark-shamy** [the-canonizer/canonizer-3.0-frontend#1188]
Remove this button from the Topic Page's mini side bar and create a button in the main blue navigation bar in (position needs to be discussed, recommended to be placed to the right of the logo).

The mobile app design proposal had this control as a central mechanism, this brings the desktop version closer to that.

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by rupalichavan9860** [comment]
Working fine on live
