### ISSUE TITLE
Error occurred while creating new topic

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#1206]
Steps to Reproduce:

- Login and click on create topic button
- Add topic name, canon and click "create topic" button
- Observe the navigated page
- "Something went wrong" error occurred

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/61a2d72d-8ba0-4c94-9d43-c125da2930c5)

**Comment by rupalichavan9860** [comment]
Same on Create new camp

**Comment by hassaanCD** [comment]
Not fixed for "Create new camp"

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on live
