### ISSUE TITLE
Error occur while change preferences in "Account setting"

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#1207]
"Cannot read properties of undefined" error occur while change preferences in "Account setting".

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/5e548c2b-1cda-4bdc-9892-01d4585e7bf5)

**Comment by hassaanCD** [comment]
Fixed

**Comment by rupalichavan9860** [comment]
Verified on live
