### ISSUE TITLE
Error occurred while click on "Recent Activity" on main page

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#1208]
As shown in attached screenshots below:

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/278fce17-1e5b-4e59-83b1-2cf730540bb8)

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/30629984-1b0a-453f-b53d-37b7caa8c240)

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Working fine on live
