### ISSUE TITLE
Unable to submit a change in camp, statement and topic

### ISSUE THREAD

**Issue by sajid315** [the-canonizer/canonizer-3.0-frontend#1215]
On staging site

- Create a topic by a user A.
- Submit a change into statement, camp or topic from user B.
- First change will be submitted on commit. 

**Problem Statement:** After first change any user is unable to submit a new change. Submit button gets disabled.

Reference Screenshot, 

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/111273633/95186eec-0ca4-4100-aea7-982230e5420a)

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/111273633/010c90df-d108-416d-98ad-6237af231eaa)

**Comment by shahab-ramzan** [comment]
@rohit-talentelgia  This ticket is related to the changes of Archive functionality, we've discussed this issue with @vikasranatalentelgia and he is looking into the issue. So i'm assigning this ticket to Vikas.

**Comment by rupalichavan9860** [comment]
Not fixed

**Comment by rupalichavan9860** [comment]
Checked after the fresh build was merged, and working fine now

**Comment by hassaanCD** [comment]
Working fine on live
