### ISSUE TITLE
Even there is "No data" available in "Recent Activity" ,there is still "View all button" visible in the bottom.

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/canonizer-3.0-frontend#1222]
![Screenshot from 2023-08-08 11-50-34](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/105647543/e9025929-fa39-40e5-b2de-d02980039713)

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on live
