### ISSUE TITLE
Multiple API calls

### ISSUE THREAD

**Issue by shahab-ramzan** [the-canonizer/canonizer-3.0-frontend#1241]
Steps to reproduce 
- go to https://canonizer3.canonizer.com/?score=0&algo=mind_experts&asof=default&canon=1
- User must be logged out 
- click on create topic from header 
- Observe API call in network tab (screen shot added for reference) 

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/96526562/1a4f6634-bdaa-4077-ae59-093678e5ba75)

**Comment by ks-rahul** [comment]
@shahab-ramzan please verify this ticket this is already fixed and change the status accordingly.

**Comment by shahab-ramzan** [comment]
@subhancd Please verify the close the ticket if it's working fine.

**Comment by subhancd** [comment]
@shahab-ramzan & @ks-rahul this is working fine on both dev and staging servers. I'm closing this ticket
