### ISSUE TITLE
When we are going in any "Topic Detail Page" and we are clicking on "Back Button" then we have to click 4 or 5 times for going at "Dashboard".

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/canonizer-3.0-frontend#1251]

**Comment by akashgit77** [comment]
![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/105647543/881b09f8-ce6b-46f3-a5a2-4eb172c54715)

**Comment by ks-rahul** [comment]
Acceptance Criteria
1. When the user clicks on the back button it should go back to the previous page if any.

@rupalichavan9860 please specify if there are any other criteria

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Working fine on live
