### ISSUE TITLE
URL is not showing properly

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#1254]
As shown in attached screenshot below

![Image](https://user-images.githubusercontent.com/120023458/263690166-22890a6f-bedc-43f8-90ce-4f5b097f37c6.png)

**Comment by hassaanCD** [comment]
**Acceptance Criteria**

**Scenario**: Incorrect URL on a Link

**Given**: I am on the canonizer homepage.

**When**: I hover over the recent activities thread and either click on it or observe the URL in the browser

**Then**:

The link should navigate to the respective thread page
The URL displayed in the browser's address bar should be valid and correspond to the expected URL structure.
The browser should not display any error messages or alerts related to the link.
The page should load within a reasonable amount of time, indicating that the URL is functional.
The navigation menu should remain accessible on the new page.
The canonizer logo or branding should be consistent with the homepage, indicating that the navigation is seamless.

**And**:

The content on the new page should match the description provided for the recent activity link.
Any interactive elements mentioned in the description should be present and functional on the thread page
The layout and design of the thread page should be consistent with the overall website's design and branding.
Any other links or interactions on the thread page should work as expected.

**Comment by hassaanCD** [comment]
Fixed

**Comment by rupalichavan9860** [comment]
Working fine on live
