### ISSUE TITLE
When we go to "Browse Page" and then we are clicking on "load more" two topics with same name were visible.

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/canonizer-3.0-frontend#1264]
STEPS:

1.GO TO CANONIZER HOMEPAGE
2.CLICK ON "BROWSE" TAB
3.SCROLL DOWN AND CLICK ON "LOAD MORE"

**Comment by akashgit77** [comment]
![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/105647543/d3d43a67-216f-4e09-86cd-d293cc665861)

**Comment by array-junkie** [comment]
PR is raised: https://github.com/the-canonizer/canonizer-service/pull/261

**Comment by sajid315** [comment]
@akashgit77 above issue has been resolved now and PR is raised for development server. Have a look please, in case of any issue please let us know.

**Comment by akashgit77** [comment]
@sajid315 working fine and tested with selenium.

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on live
