### ISSUE TITLE
Info icon is not in correct place in mobile view

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#1268]
Info icon is not in correct place in mobile view as shown in attached screenshot:

![Image](https://user-images.githubusercontent.com/120023458/267359774-27adf88c-e394-4822-bf2d-f10fca1d1360.png)

**Comment by hassaanCD** [comment]
"As of date filter" is not aligned in mobile view as shown in attached screenshot below:


![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/545ce04b-ce40-4939-96cb-17c4acd5a1db)

**Comment by subhancd** [comment]
verified on development server

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by saniatg** [comment]
verified on production
