### ISSUE TITLE
UI issues in "Camp Statement History" page and "Compare statement" page

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#1278]
UI issues in "Camp Statement History" page and in "Compare statement" page as shown in attached screenshots below:

![Image](https://user-images.githubusercontent.com/120023458/268004403-99dc0802-babd-46a8-be4e-f98f8c1de515.png)

![Image](https://user-images.githubusercontent.com/120023458/268004447-0b4b7f4f-bab8-4e16-b2fb-36abd6a3adb1.png)

**Comment by subhancd** [comment]
fixed. verified on development server

**Comment by akashgit77** [comment]
@shahab-ramzan After clicking on "compare" button without login its redirecting to login page.is that okay?

**Comment by rupalichavan9860** [comment]
Working fine on live
