### ISSUE TITLE
remove extra "get-camp-breadcrumbs" api call from topic detail page

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/canonizer-3.0-frontend#1284]
**Steps to reproduce**
1. login with valid credentials
2. navigate to any topic detail page
3. check the network call

**Actual Result**
"get-camp-breadcrumbs" api is called twice

**Expected Result**
api should be called only once

**Comment by subhancd** [comment]
@ks-rahul is it deployed on development server? there are still api calls for "get-camp-breadcrumbs" api

**Comment by rupalichavan9860** [comment]
Working fine now
