### ISSUE TITLE
Support Removing on Multi-Clicks

### ISSUE THREAD

**Issue by sajid315** [the-canonizer/canonizer-3.0-frontend#1285]
Steps to reproduce this issue:
1 - Go to staging canonizer.
2-  Create new topic and make three camps in it by adding support as well. 
3-  Now go to account settings and change order of camps. 
4-  On opening of reason popup after save changes, hit the "Submit" button multiple times. 

Expected Result: Button should be disabled after one click. 

Here below is the screencast for reference.

https://www.awesomescreenshot.com/video/20927433?key=b8e150c16b74147efab1d77512417940

**Comment by subhancd** [comment]
fixed. verified on development server.

**Comment by rupalichavan9860** [comment]
Verified on live
