### ISSUE TITLE
"Camp Tree" is ambiguous.

### ISSUE THREAD

**Issue by shahab-ramzan** [the-canonizer/canonizer-3.0-frontend#1296]
![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/6559312/59129306-2625-4d56-ab27-ad1f8cb3768c)

Since there are not supporters for this camp, it says:  "No Camp Tree Found"
But "camp tree" could also mean the supporting sub camps of this camp.

There should be both a "camp tree" (supporting sub camps) and a "support tree" (delegation tree).

And I think the best message in this situation would be: **"No supporters of this camp"**

**Comment by subhancd** [comment]
verified on development server

**Comment by subhancd** [comment]
verified on staging

**Comment by hassaanCD** [comment]
Verified on production
