### ISSUE TITLE
Hyperlinks in camp statements should default to a different color.

### ISSUE THREAD

**Issue by shahab-ramzan** [the-canonizer/canonizer-3.0-frontend#1297]
The second line in this statement is a hyperlink, but you can't tell.

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/6559312/bbb819b5-da52-4f4b-bc8f-6a8371b55e50)

**Comment by rupalichavan9860** [comment]
Closing this ticket because it was user error and not a problem, as discussed in the meeting.
