### ISSUE TITLE
Popup placement for camp on previous date

### ISSUE THREAD

**Issue by sajid315** [the-canonizer/canonizer-3.0-frontend#1299]
We need to display popup at both places (In side panel and on page of topic detail)

I observed that on local system its showing the pop up inside the side panel, and on staging its showing at topic detail page. Following are the screenshots.

![image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/111273633/42af1d46-b35d-4129-8aab-c0e3077f8823)

![image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/111273633/e00634a8-124b-4d34-a148-c305f8b69c0b)

**Comment by sajid315** [comment]
@rupalichavan9860 can you please confirm above changes required in this ticket ?

**Comment by rupalichavan9860** [comment]
Yes @sajid315 . Can you please do the same for topic created date as well?

**Comment by sajid315** [comment]
@ks-rahul  Yes for topic creation here below is the screenshot.
![image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/111273633/100902cc-4e3a-417c-9167-f5fbb93fab99)

**Comment by rupalichavan9860** [comment]
Yes Topic created date link is available here but not on topic detail page . So please add the same on topic detail page

**Comment by rupalichavan9860** [comment]
Verified on development and staging server

**Comment by rupalichavan9860** [comment]
Verified on live
