### ISSUE TITLE
User Profile Page : only show one error message for incorrect nick name id in the URL

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/canonizer-3.0-frontend#1303]
**Steps to reproduce**

1. navigate to any topic
2. navigate to manage support
3. click on any user nick name
4. change the nick name id in the URL

**Actual Result**

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/104552751/c70ab834-84bd-4ab4-8844-ff3f85926b5f)

**Comment by subhancd** [comment]
this ticket is dependent on ticket#569 and cannot be tested until that issue is resolved

**Comment by subhancd** [comment]
still 2 error message are displayed


![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/104552751/165fc974-6c2c-4f91-8b5f-cd9c1ca5590b)

**Comment by DevAlchemyCD** [comment]
https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1341 
@subhancd  vikas pushed the changes in above pr

**Comment by subhancd** [comment]
@wahaj-hafeez for user profile, change it to user not found


![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/104552751/2fd7e44b-8932-4531-bb51-143832236bb9)

**Comment by DevAlchemyCD** [comment]
pr for ticket  : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1422

**Comment by hassaanCD** [comment]
Verified on development

**Comment by hassaanCD** [comment]
Working fine on production
