### ISSUE TITLE
When clicks on the any topic or canonizer.com, the default value of should not be included in the URL query string.

### ISSUE THREAD

**Issue by ashish76** [the-canonizer/canonizer-3.0-frontend#1329]
When we click on canonizer.com or any topic, the URL includes the following information in the URL as a query string with a default value. The query string should be attached if the user changes the value.
- score 
- algo
- asof
- canon

For example https://canonizer.com/?score=0&algo=blind_popularity&asof=default&canon=1
This should only attached when the user makes the changes in any of the above parameters.

**Comment by rupalichavan9860** [comment]
This is implemented on development ,staging and live . Will log issues separately if any
