### ISSUE TITLE
On Forum Page, Threads not not showing on new tab options (When user Right Click on the thread list)

### ISSUE THREAD

**Issue by akuks** [the-canonizer/canonizer-3.0-frontend#1346]
On the Forum Page, when users attempt to right-click on a thread from the thread list, the option to open the thread in a new tab is not appearing. This limits the user's ability to simultaneously view multiple threads and may hinder their browsing experience.

- It appears that the 'Open in a new tab' option is conspicuously absent when a user right-clicks on any thread from the list. 
- Many users rely on this functionality to open multiple threads simultaneously,

**Comment by rupalichavan9860** [comment]
Working fine on development server

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by rupalichavan9860** [comment]
Verified on live
