### ISSUE TITLE
Eventline -  all eventlink have (is_tree_open=1) open tree expect history page

### ISSUE THREAD

**Issue by sunilspr7** [the-canonizer/canonizer-3.0-frontend#1352]
add this parameter in url = is_tree_open=1

Example : https://development.canonizer.com/topic/3426-issue-531-archive/2-c1?asof=bydate&filter=0&asofdate=1699426787&viewversion=1&is_tree_open=1

**Comment by DevAlchemyCD** [comment]
pr for this  ticket : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1358

**Comment by saniatg** [comment]
working fine on development

**Comment by akashgit77** [comment]
working fine on the production.
