### ISSUE TITLE
Change "Recent Activities" to "Current Camp Recent Activities"

### ISSUE THREAD

**Issue by rohit-talentelgia** [the-canonizer/canonizer-3.0-frontend#1355]
On the topic page, change the heading "Recent Activities" to "Current Camp Recent Activities"

![image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/8575740/f995f70a-0177-49c6-b618-a82d995062ca)

**Comment by hassaanCD** [comment]
Verified on development

**Comment by hassaanCD** [comment]
Verified on production

**Comment by hassaanCD** [comment]
Verified on production
