### ISSUE TITLE
Show Profile picture on user support profile page

### ISSUE THREAD

**Issue by shahab-ramzan** [the-canonizer/canonizer-3.0-frontend#1378]
![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/96526562/98b16340-9a8d-4bdb-8cbb-40d6b9b644ec)

**Comment by rupalichavan9860** [comment]
Implemented on development server

**Comment by DevAlchemyCD** [comment]
@rupalichavan9860 Profile pic have been displayed if the respective user has a Profile pic

**Comment by rupalichavan9860** [comment]
Verified on development and live server

**Comment by rupalichavan9860** [comment]
Verified on live
