### ISSUE TITLE
Handling of URL for cases of undefined values

### ISSUE THREAD

**Issue by sajid315** [the-canonizer/canonizer-3.0-frontend#1390]
We need to address the link issue added in the below ticket.

https://github.com/the-canonizer/canonizer-3.0-api/issues/845

Also sometimes opening the canonizer.com site automatically appends query string as discussed with @ks-rahul.

**Comment by ks-rahul** [comment]
@sajid315 if the filter value is not the default value then the query string will append automatically. this is implemented like this.

**Comment by sajid315** [comment]
@ks-rahul so other than default value this will include "undefined" in filter? I think we should handle case of undefined and NULL values. As we discussed in call about redux state as well.

Here below is another place where i got undefined in tree camp URL.
![image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/111273633/0fb4f25a-220d-4a2f-bb25-cd9b57d2d5c0)
