### ISSUE TITLE
Add "id" attribute for profile image (upload input) + Selenium TestCase

### ISSUE THREAD

**Issue by sajid315** [the-canonizer/canonizer-3.0-frontend#1402]
@wahaj-hafeez  we need to add "id" attribute for user profile image up-loader HTML to track X PATH of up loader.

@akashgit77 as we discussed following are the rules and parameters we are checking at back-end, 

- Mime Type must be : jpg, jpeg, png

**Comment by DevAlchemyCD** [comment]
@akashgit77 
I have added the ( id="upload-profile" ) attribute for the profile image uploader. You can utilize this for image uploader x path. Also following are the validation parameters for the image at the front end.

MAX_IMAGE_WIDTH = 1000 px
MAX_IMAGE_HEIGHT = 1000 px
The file type must be an image

Let me know in case of any query, please.
