### ISSUE TITLE
After creating new post ,Date is invalid.And when we already in Post page and we login then post "edit" & "delete" options are not updating according to the user.

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/canonizer-3.0-frontend#1410]

**Comment by akashgit77** [comment]
![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/105647543/3932c272-bb49-4de3-b8b6-61fff4affaa7)

**Comment by hassaanCD** [comment]
Not fixed. "Session expired" error and logged out on clicking "Submit" button in post popup.

**Comment by ks-rahul** [comment]
@hassaanCD PR has been raised for the logout issue.

**Comment by saniatg** [comment]
working fine on development

**Comment by akashgit77** [comment]
@saniatg @rupalichavan9860 we are not able to create new topic, still facing issues on the development server.

**Comment by saniatg** [comment]
working fine on production, there is issue with the date. Will log that issue separately and link here
https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/issues/878
