### ISSUE TITLE
When we are going to topic comparison page,then "Invalid Date" showing for a moment.

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/canonizer-3.0-frontend#1411]

**Comment by akashgit77** [comment]
![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/105647543/1246e9f5-6ef3-4b0a-9071-424dd5dfc138)

**Comment by saniatg** [comment]
working fine on development

**Comment by akashgit77** [comment]
Working fine the production.
