### ISSUE TITLE
Global Search: While entering the keywords, it is showing "No Data" for a moment before existing data appears.

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/canonizer-3.0-frontend#1416]
We should show loader instead of "No Data Found".

**Comment by akashgit77** [comment]
![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/105647543/7ca8942a-0ebf-434f-9091-1adff65800b2)

**Comment by saniatg** [comment]
@vikasranatalentelgia  the same issue is on pages when click ->' all ,  topic, camp, camp statement or nickname, please implement for these pages as well.
![Screenshot 2023-12-18 at 5 11 52 PM](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/91254708/2d442f16-b5a3-43f7-9fba-0e337a150c80)

**Comment by saniatg** [comment]
@vikasranatalentelgia this issue where no data found shows for a sec and then disappears is still showing sometimes. There is no specific case but I saw it 2-3 times. Please have a look

**Comment by saniatg** [comment]
working fine on development

**Comment by akashgit77** [comment]
@saniatg I am still facing the issue

https://github.com/the-canonizer/canonizer-3.0-frontend/assets/105647543/77da22ce-b5ce-4e96-82c1-c9bd1a7eba0c

**Comment by akashgit77** [comment]
Working fine on the production.
