### ISSUE TITLE
Page is crashing while logging out on the "Canonizer3" server.

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/canonizer-3.0-frontend#1443]

**Comment by akashgit77** [comment]
![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/105647543/d0529ff2-af32-4579-8625-09f97d445f80)

**Comment by ks-rahul** [comment]
@akashgit77 this is working fine now

**Comment by rupalichavan9860** [comment]
Working fine on all environment
