### ISSUE TITLE
Event Line - Add skeleton in play, forward, backwards, and speed buttons when page is loading

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#1476]
![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/54114d00-6efe-4bad-b23d-238a5e4e5eb4)

**Comment by DevAlchemyCD** [comment]
pr : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1477

**Comment by hassaanCD** [comment]
Verified on development

**Comment by hassaanCD** [comment]
Working fine on production
