### ISSUE TITLE
UI issues - "Topic detail" and "Create topic" page

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#1480]
![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/4353c5f7-b874-40d6-a07b-88f9863c5f5e)

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/bb39f2f2-8bc8-43e9-9fbe-2dd613e5b6e7)

**Comment by hassaanCD** [comment]
Verified on development

**Comment by saniatg** [comment]
Working fine on production
