### ISSUE TITLE
When user click on "Directly join or support" button, then popup will open

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#1486]
![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/76b8bb12-3c9d-46d0-a19d-909d9a06678a)

**Comment by rupalichavan9860** [comment]
Pop up is implemented and we will log issues separately if any

**Comment by hassaanCD** [comment]
Implemented on production

**Comment by hassaanCD** [comment]
Implemented on production
