### ISSUE TITLE
When user click on "Delegate your support" button, then popup will open

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#1487]
![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/c8624b0b-5304-41d4-a380-47a22a92c05a)

**Comment by rupalichavan9860** [comment]
Pop up is implemented and we will log issues separately if any

**Comment by hassaanCD** [comment]
Pop up is implemented on production
