### ISSUE TITLE
Design implementation for the advanced filter for topic section

### ISSUE THREAD

**Issue by rohit-talentelgia** [the-canonizer/canonizer-3.0-frontend#1490]
Implement the design for the advanced filter for the topic section:

https://xd.adobe.com/view/fd089c71-f4a0-4c79-a3ae-8a748bd02b94-a85b/screen/0c7605cf-37d4-4d29-a4ed-211d58fff41c/?fullscreen

**Comment by saniatg** [comment]
working fine on production
