### ISSUE TITLE
Design implementation for the advanced filter for Camp section

### ISSUE THREAD

**Issue by rohit-talentelgia** [the-canonizer/canonizer-3.0-frontend#1491]
Implement the design for the advanced filter for the camp section:

https://xd.adobe.com/view/fd089c71-f4a0-4c79-a3ae-8a748bd02b94-a85b/screen/c5fe5c4e-64e8-423b-a663-8c524aae1f6f?fullscreen

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
working fine on production
