### ISSUE TITLE
Design implementation for the advanced filter for Statement section

### ISSUE THREAD

**Issue by rohit-talentelgia** [the-canonizer/canonizer-3.0-frontend#1492]
Implement the design for the advanced filter for the statement section:

https://xd.adobe.com/view/fd089c71-f4a0-4c79-a3ae-8a748bd02b94-a85b/screen/85bf72f3-9daf-4dcf-9c8a-7bfc029358e5?fullscreen

**Comment by saniatg** [comment]
working fine on production
