### ISSUE TITLE
Design implementation for the advanced filter for Nickname section

### ISSUE THREAD

**Issue by rohit-talentelgia** [the-canonizer/canonizer-3.0-frontend#1493]
Design implementation for the advanced filter for Nickname section

https://xd.adobe.com/view/fd089c71-f4a0-4c79-a3ae-8a748bd02b94-a85b/screen/827ede99-ce75-476e-a3db-93759e22eaf3?fullscreen

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
working fine on production
