### ISSUE TITLE
Search is not working on development server

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#1496]
As shown in attached screenshot:

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/51107fbe-bc2c-43c4-88da-bb0cd256a07a)

**Comment by DevAlchemyCD** [comment]
pr : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1497

**Comment by rupalichavan9860** [comment]
Working now on development server

**Comment by saniatg** [comment]
Not fixed on development

**Comment by DevAlchemyCD** [comment]
@saniatg ! I have tested it on the development server. It is working fine there.

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/99801525/df55da6c-db66-4255-9740-73094f62cf00)

**Comment by rupalichavan9860** [comment]
Working fine on development server

**Comment by rupalichavan9860** [comment]
Verified on live
