### ISSUE TITLE
Remove "delegate support" button is not working

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#1500]
As shown in attached screenshot

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/167a9420-6d80-4a91-acc5-6102aeebfafb)

**Comment by DevAlchemyCD** [comment]
pr : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1505

**Comment by hassaanCD** [comment]
Not fixed. Not working when user click first time on "Remove" button. It works when user refresh the page.

**Comment by DevAlchemyCD** [comment]
@hassaanCD The pull request has not been merged yet, that's why it's working

**Comment by saniatg** [comment]
working fine on developement

**Comment by saniatg** [comment]
working fine on production
