### ISSUE TITLE
Duplicate API calls when user delegate support

### ISSUE THREAD

**Issue by DevAlchemyCD** [the-canonizer/canonizer-3.0-frontend#1506]
![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/99801525/91076773-7496-40fd-9f76-854f9f9e7fa3)

**Comment by DevAlchemyCD** [comment]
pr : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1505

**Comment by hassaanCD** [comment]
Not fixed.



![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/05aaa1d9-05fa-4264-a40f-759a29fcd707)

**Comment by DevAlchemyCD** [comment]
@hassaanCD The pull request has not been merged yet, that's why it's working

**Comment by hassaanCD** [comment]
Not fixed.


![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/314ef4bc-edfb-474d-88f0-99c16708bbc0)

**Comment by hassaanCD** [comment]
Not fixed


![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/e9a8bcb9-af6b-4d86-a097-303c9b047abd)

**Comment by hassaanCD** [comment]
Working fine on production
