### ISSUE TITLE
Display name issue on "User Profile" page

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#1508]
Steps to Reproduced:
1. Login with user A
2. Go to "Account Settings"
3. Public "First and Second Name" fields
4. Private all other fields
5. Click "Update"
6. Navigate to "User Profile" page
7. Observe User Information section

Result: Display name is not showing properly as shown in attached screenshot 

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/fb76c406-3a36-43fb-bdfe-10908fbc5caa)

**Comment by DevAlchemyCD** [comment]
pr : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1510

**Comment by rupalichavan9860** [comment]
Working fine on development server

**Comment by saniatg** [comment]
working fine on production
