### ISSUE TITLE
Notification clicks are not working

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#1509]
Steps to Reproduced:

1. Login with User A
2. Click on "Notification" icon
3. Click on any past day notification from dropdown
4. Observe the page

Result: Blank page is showing as shown in attached screenshots

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/b4a323fb-ab2a-4894-bb67-9bd94ea41c7a)

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/7ef24f72-ed1d-47f7-a756-3ec83117a9b5)

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
working fine on production
