### ISSUE TITLE
Multiple API calls on "Topic Detail" page

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#1514]
Please refer to attached video link:
https://www.loom.com/share/8e592ca2fa2d46ebbdc10a21a217afc3?sid=70159f49-8c93-441d-950d-51b5f642c7d7

**Comment by DevAlchemyCD** [comment]
pr  : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1517

**Comment by hassaanCD** [comment]
Not fixed.


![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/94c0a0b4-0a05-4f48-99d5-34e206aa5c33)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1662

**Comment by hassaanCD** [comment]
Not fixed


![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/3bdb3aed-33cf-49de-a735-95c7a44dcdb8)

**Comment by DevAlchemyCD** [comment]
@hassaanCD  ! I have verified this issue on development. It is working fine there. 


![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/99801525/e243c171-a09f-40d2-9877-86b3300aeefd)

**Comment by rupalichavan9860** [comment]
Verified on development server

**Comment by hassaanCD** [comment]
Not fixed on production


![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/91f31cf0-e4e3-488f-9f7a-a223b5ed482d)

**Comment by DevAlchemyCD** [comment]
@hassaanCD ! I have verified it on production. It is working fine there.

**Comment by hassaanCD** [comment]
Working fine on production
