### ISSUE TITLE
Consensus Tree: When get API is in progress then "100 % score" checkbox must be disable

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#1515]
Please refer to attached screenshot:

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/2f1028aa-3f5d-479f-90d6-04dbbc7587f9)

**Comment by DevAlchemyCD** [comment]
pr : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1533

**Comment by hassaanCD** [comment]
Working fine on development

**Comment by hassaanCD** [comment]
Working fine on production
