### ISSUE TITLE
"Directly Join and Support" button is clickable outside the "button"

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#1516]
"Directly Join and Support" button is clickable outside the "button" is clickable in the mentioned area. Please refer to attached screenshot:

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/f39c79de-9fea-4f7d-a085-8222996d78aa)

**Comment by DevAlchemyCD** [comment]
pr : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1519

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
working fine on production
