### ISSUE TITLE
Support modal is opening on notification click

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#1521]
As refer to attached video link:

https://www.loom.com/share/afc908b251314967b0483f6623b4b2c3?sid=f6eed01d-a5b6-42f7-b16f-ea40af451906

**Comment by DevAlchemyCD** [comment]
pr : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1599

**Comment by hassaanCD** [comment]
Not fixed

**Comment by wahaj-hafeez** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1708

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1709

**Comment by hassaanCD** [comment]
Working fine on development

**Comment by hassaanCD** [comment]
Working fine on production
