### ISSUE TITLE
Cursor loses it focus after the search results

### ISSUE THREAD

**Issue by akuks** [the-canonizer/canonizer-3.0-frontend#1523]
- Go to "https://canonizer.com/browse"
- Click on Search Box "Search by Topic Name"
- Write 2 or 3 characters like "Art" and wait till the results are popped up
- Cursor pointer loses its focus from the search box. If we want to type again, then we need to click on the search box

**Comment by saniatg** [comment]
working fine on development

**Comment by hassaanCD** [comment]
Working fine on production

**Comment by saniatg** [comment]
working fine on production
