### ISSUE TITLE
Api error on changing as of date filter to default and vice versa

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer-3.0-frontend#1525]
![Screenshot 2024-02-01 at 1 24 20 PM](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/91254708/6b1df5ba-a39d-4e45-b2dd-e220c920b2a1)
  when switching between as of date and default filter , api errors are seen in console

**Comment by sajid315** [comment]
@saniatg both API's are showing "404 not found" error, that is relevant to "No Data Found" in camp statement and camp news feed. So its actually not an issue to be addressed. 
Whenever no data will be found for any specific API, we are returning status as **"404"**
