### ISSUE TITLE
UI Issue: Location of tooltip is not right

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#1526]
As shown in attached screenshots:

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/5ea27a4c-ff58-47b6-b44e-59b9f85df324)

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/ffb9dc6a-6b4a-4a4e-ba47-d050ab810648)

**Comment by DevAlchemyCD** [comment]
pr : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1535

**Comment by saniatg** [comment]
@wahaj-hafeez not fixed on development
![Screenshot 2024-02-08 at 8 38 24 PM](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/91254708/ecdd49e6-64d5-4348-abc3-f692d689fd9e)

**Comment by saniatg** [comment]
working fine now on development

**Comment by hassaanCD** [comment]
Working fine on production
