### ISSUE TITLE
Commit and cancel button fluctuates on history pages

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer-3.0-frontend#1531]
Steps:

1. Click on button "manage /edit statement or camp or topic 
2. As a user you will see commit and cancel button is disabled for 1 sec and immediately  enables.

As per user experience it should be smooth

![Screenshot 2024-02-05 at 1 40 58 PM](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/91254708/deb0b977-3dbb-43e6-a60c-b0537adf9ec8)

**Comment by DevAlchemyCD** [comment]
pr : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1536

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
working fine on production
