### ISSUE TITLE
change "no supporters" to "no direct supporters"

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#1538]
If there are no direct supporters of a camp, it says: "No supporters of this camp" in the support section of a camp page.
This should say no direct supporters.
Without this it can be confusing if there are implicit supporters through sub camps, which are supporters, just not direct.

**Comment by DevAlchemyCD** [comment]
pr : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1545

**Comment by hassaanCD** [comment]
Working fine on development

**Comment by hassaanCD** [comment]
Working fine on production
