### ISSUE TITLE
UI Issue: There is space between "Topic name" filed and "Topic Already Exists" error message

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#1543]
As shown in attached screenshot:

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/5e3eb538-db99-442a-900d-d22b7c9e3c7f)

**Comment by DevAlchemyCD** [comment]
pr : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1545

**Comment by rupalichavan9860** [comment]
Working fine on development server

**Comment by saniatg** [comment]
Error message has been changed now
