### ISSUE TITLE
Submit button should be disabled on "Directly Join and support"

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#1546]
Steps to Reproduce:
- Create a topic
- Refresh the page
- Click on "Directly join and Support"

A modal will open with enabled "Submit" button and then disappear and reload the data.
If we managed to click "Submit" button before reload, it will remove already added support.

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/dbba08eb-de1f-434e-9f28-677bad7a6401)

**Comment by DevAlchemyCD** [comment]
pr : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1552

**Comment by saniatg** [comment]
@wahaj-hafeez not fixed on development

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1684

**Comment by saniatg** [comment]
working fine on development

**Comment by hassaanCD** [comment]
Working fine on production
