### ISSUE TITLE
The support link in the Dropdown is not disabled on the "as of date" filter selected.

### ISSUE THREAD

**Issue by ks-rahul** [the-canonizer/canonizer-3.0-frontend#1547]

**Comment by ks-rahul** [comment]
This issue has been fixed but the code is not merged yet.

**Comment by rupalichavan9860** [comment]
@ks-rahul The link is disabled, but the user may still click on it and it opens a pop-up.
![image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/40416610/120ad681-2916-4537-9fca-1b98b353850e)

**Comment by saniatg** [comment]
working fine on development

**Comment by hassaanCD** [comment]
Working fine on production
