### ISSUE TITLE
Threads Tooltip: Dots are appending by the end of thread messages

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#1550]
As shown in attached screenshots:

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/f98bdba9-c929-415f-a058-780556e23c0c)

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/4469d662-46e7-4fed-a894-6701ad619c31)

**Comment by DevAlchemyCD** [comment]
pr : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1554

**Comment by hassaanCD** [comment]
Working fine on development

**Comment by hassaanCD** [comment]
Working fine on production
