### ISSUE TITLE
Hide username  from header

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#1551]
![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/276990d8-c137-4a6d-a212-6b0f6a889c16)

**Comment by DevAlchemyCD** [comment]
pr : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1552

**Comment by saniatg** [comment]
working fine on development

**Comment by hassaanCD** [comment]
Working fine on production
