### ISSUE TITLE
Create Topic: Error message must be shown when user enter empty spaces

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#1562]
When user login and create new topic by entering empty spaces in "Topic Name" field. Then error message must be shown. As shown in attached screenshot:

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/c8876476-cb30-4992-8dee-8fa79345f69c)

**Comment by DevAlchemyCD** [comment]
pr : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1564

**Comment by rupalichavan9860** [comment]
Verified on dev server

**Comment by hassaanCD** [comment]
Working fine on production
