### ISSUE TITLE
Multiple API calling on "Browse" page

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#1563]
Step to reproduce:

- Login and create topic
- Navigate to "Browse" page.
- You can see Multiple "getAll" APIs as shown in the attached screenshot:

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/92fdba1e-ee27-4b5d-a6b8-8285a79975ef)

**Comment by DevAlchemyCD** [comment]
pr : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1564

**Comment by hassaanCD** [comment]
Working fine on development

**Comment by hassaanCD** [comment]
Working fine on production
