### ISSUE TITLE
Click is enable on "disabled" buttons in "Topic Detail" page

### ISSUE THREAD

**Issue by gautamv16** [the-canonizer/canonizer-3.0-frontend#1571]
Steps to reproduce:

Login with any user
Select any topic from main page
Select "In Review" from filter
Click on 3 dots on "Topic Detail" page
Click on disabled button from drop down like "Manage Support"
"Manage Support" is opening while clicking on disabled "Manage Support" button

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/6199964/0d7ac472-7fba-4f74-92f0-e6268cb86b95)

**Comment by DevAlchemyCD** [comment]
@gautamv16  this ticket works fine

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
working fine on production
