### ISSUE TITLE
Development: "Remove your Support" button appear again after click for first time

### ISSUE THREAD

**Issue by gautamv16** [the-canonizer/canonizer-3.0-frontend#1572]
As shown in attached screenshot:

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/6199964/50cc5c22-9ce5-4b63-a019-4104edecbce4)

**Comment by DevAlchemyCD** [comment]
@gautamv16 I tried to reproduce this issue but I'm not able to reproduce it. Can you please check it again and reverify?

**Comment by hassaanCD** [comment]
Not fixed


![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/129f1932-207f-43fe-b70a-6efcffaf71bf)

**Comment by DevAlchemyCD** [comment]
@hassaanCD ! I have tested it on development. It is working fine there.

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/99801525/f60a90b3-8528-45c4-b646-4e2a1632e39e)

**Comment by saniatg** [comment]
working fine for now on development
