### ISSUE TITLE
Show selected filter on topic/camp page

### ISSUE THREAD

**Issue by rohit-talentelgia** [the-canonizer/canonizer-3.0-frontend#1582]
As a user, I should be able to view the selected filters and on click of the cross icon, the filter should be removed and set to default, as per the below design.

![Topic-Filters](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/8575740/35ed610f-a6a2-43e9-a1e0-c3b057ce356a)

**Comment by rupalichavan9860** [comment]
Functionality has been implemented. We will log the issue separately, if any.

**Comment by saniatg** [comment]
Functionality implemented on live
