### ISSUE TITLE
Error while creating "New Topic"

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#1583]
Steps to Reproduce:
Sign in with any user and click on "Create topic"
First type name of already existing topic like "ABC"
Then error "Topic Title already exist" will show and link of already existed topic will appear under the field
Then change the name to "ABCD"
And click on "create top" button
Then error "Topic Title already exist" and link will show again with topic created successfully

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1588

**Comment by saniatg** [comment]
working fine on development

**Comment by hassaanCD** [comment]
Working fine on production
