### ISSUE TITLE
Create topic page appears for one second and then disappear when a logged out user clicks on "Create Topic" button

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#1608]
When a logged out user clicks on "Create Topic" button, then create topic page appears for one second and then login page appears.

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1614

**Comment by saniatg** [comment]
working fine on development

**Comment by hassaanCD** [comment]
Working fine on production
