### ISSUE TITLE
Live: When user select "Default" it is showing "Agreement", when user select "Include Review" it is showing "Topic Name"

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#1623]
As shown in attached screenshots:

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/edb030cd-e483-4e4d-97b5-e706e5ba999b)

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/a2849d82-e706-4d75-9c40-71fe12ddd912)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1819

**Comment by rupalichavan9860** [comment]
Verified on development server

**Comment by hassaanCD** [comment]
Working fine on production
