### ISSUE TITLE
Live: Show error message "Camp not found" on specific scenario

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#1627]
Steps to reproduce:
Login and create new topic
Click on create camp and navigate to "Create new Camp" page
You can see this URL on the "Create new Camp" page https://canonizer.com/camp/create/972-77777/1-Agreement
Replace 1 with any number like "100" in the URL like https://canonizer.com/camp/create/972-77777/100-Agreement
And press enter
It will show number "100" in "Parent Camp" field
Expected Result: 

- It must show error message "Camp not found"
- Also handle the backend API after submission of form in this scenario.
- "Page Not Found" must be shown if "Camp Id" does not exist.

As shown in attached screenshot:

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/18a3f6d4-6b64-4196-b26c-af900684663d)

**Comment by DevAlchemyCD** [comment]
pr : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1639

**Comment by hassaanCD** [comment]
Working fine on development

**Comment by saniatg** [comment]
Working fine on production
