### ISSUE TITLE
Restrict Update Profile Page + Restrict Infinite API Calls to Meta Tags

### ISSUE THREAD

**Issue by sajid315** [the-canonizer/canonizer-3.0-frontend#1628]
Steps to produce:
1- Open Canonizer production in private window. 
2- Sign In to canonizer using google account. 
3- Go to Account Settings. 
4- On profile update page, click on logout at same state.

Actual Results: 
User will be logged out but the account settings page still remains same. And in network we can see infinite meta tags API calls.

Expected Results:
It should restrict the account settings page after logout and we have to remove infinite API calls.

Reference Screenshot:
![image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/111273633/1508f639-efc3-42e4-a5a2-f33471526026)

**Comment by hassaanCD** [comment]
Working fine on development

**Comment by hassaanCD** [comment]
Working fine on production
