### ISSUE TITLE
Remove "get-statement-history" API from topic detail page

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#1640]
Steps to reproduce
1- Open Canonizer.com, go to any topic and open inspect mode.
2- Click on "Include Review". 

Actual Results:
Irrelevant API call of get-statement-history on topic detail page.

Expected Results:
We should remove statement history API.

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/dbbe4856-7581-4c37-967a-029e985414d1)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1650

**Comment by hassaanCD** [comment]
Working fine on development

**Comment by hassaanCD** [comment]
Working fine on production
