### ISSUE TITLE
Camp About Nickname: Add cross button to remove already selected Nickname

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#1656]
When user selected a Nickname in "Camp About Nickname" dropdown, there is no any way to remove the already selected Nickname. 
Cross button must be added in "Camp About Nickname" dropdown.
As shown in attached screenshot:

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/9ab020a0-0800-40e6-926e-c4d7af05c1ce)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1658

**Comment by saniatg** [comment]
working fine on development

**Comment by saniatg** [comment]
Working fine on production
