### ISSUE TITLE
Page is crashing on development when we open any topic in private window via copy/paste of URL

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#1672]
![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/6e3e61ef-352a-421b-8591-dd217c5ca545)

**Comment by DevAlchemyCD** [comment]
pr : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1674

**Comment by saniatg** [comment]
working fine on development

**Comment by rupalichavan9860** [comment]
Verified on live
