### ISSUE TITLE
Dev: Logged out user not able to click on "Create Topic" button

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#1673]
Logged out user not able to click on "Create Topic" button. User must navigate to "Login" page.

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1680

**Comment by saniatg** [comment]
@wahaj-hafeez working but must redirect to create topic page not home page

**Comment by rupalichavan9860** [comment]
> @wahaj-hafeez working but must redirect to create topic page not home page

Main issue is working fine , for redirect I have logged new ticket
Please refer : https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/issues/910

**Comment by saniatg** [comment]
working fine on production
