### ISSUE TITLE
Create "video page" in canonizer

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#1686]
As discussed in today's meeting:
" Can we do something so [canonizer.com/videos](http://canonizer.com/videos) provides an index page with a link to the consciousness folder instead of a 404 error?  Eventually we may have links to other videos in the folder?"

**Comment by DevAlchemyCD** [comment]
Implementing the  video page design on the frontend

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1758

**Comment by sajid315** [comment]
Following is the PR from backend,
https://github.com/the-canonizer/canonizer-3.0-api/pull/1007

**Comment by rupalichavan9860** [comment]
Verified on development server

**Comment by hassaanCD** [comment]
Working fine on production
