### ISSUE TITLE
It is showing "remove your support" instead of "delegate your support" when user not logged in

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#1723]
When user copy link of any topic detail page with "direct" and "delegate" support already added and paste it in new browser with user not logged in then why it is showing "remove your support" instead of "delegate your support". 
As shown in attached screenshot:

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/8eb359e0-d081-4211-8a52-b8a3cb4d08c4)

**Comment by DevAlchemyCD** [comment]
PR : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1733

**Comment by hassaanCD** [comment]
Working fine on development

**Comment by hassaanCD** [comment]
Working fine on production
