### ISSUE TITLE
Support Camps modal UI issue

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#1749]
UI issue occurred when user open "Nick Name" drop down of "Support Camps" modal and without selecting nickname scroll up and down.
As shown in attached screenshot:

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/9a258e36-5124-43b0-b9fc-fe18768989d1)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1759

**Comment by saniatg** [comment]
working fine on development

**Comment by hassaanCD** [comment]
Working fine on production
