### ISSUE TITLE
"Archived" topic is not searched when "Show Archived Camps" filter is applied

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#1755]
As shown in attached screenshot:

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/c2cbbd2a-45c1-4038-8917-1a284c0a264a)

**Comment by DevAlchemyCD** [comment]
PR : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1761

**Comment by hassaanCD** [comment]
Working fine on development

**Comment by hassaanCD** [comment]
Working fine on production
