### ISSUE TITLE
Implement social Share Feature for Eventline

### ISSUE THREAD

**Issue by DevAlchemyCD** [the-canonizer/canonizer-3.0-frontend#1762]

**Comment by hassaanCD** [comment]
@wahaj-hafeez We need to fix issue when the URL has multiple Query params. 
Fix the footer in case of single event.
Twitter icon also needed to be updated as "X"

**Comment by DevAlchemyCD** [comment]
Ok @hassaanCD I am going to fix

**Comment by wahaj-hafeez** [comment]
@BrentAllsop I also checked for the requirement of increasing speed for the event-line animation. So currently the library we have used for this Slider (Animation Pointer) provides a marking value of 100 maximum. As you can see in the following screenshot.

And currently, we divided this speed of 100 into 4 parts: 0 (0.5x), 25 (0.75x), 50 (1x), 75 (1.25x), 100 (1.5x)

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/99801525/4288de78-50e8-4c95-84f5-5b6b85e5ef24)

So If we have to add more Playback speeds then we have to do the following, 
1- Update UI 
2- Divide 100 into the required number of speed patterns.

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1777

**Comment by hassaanCD** [comment]
Working fine on development

**Comment by hassaanCD** [comment]
Working fine on production
