### ISSUE TITLE
Duplicate API call when user select from search dropdown

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#1763]
![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/adab4b13-f2fe-4bfb-a548-28c75f092dac)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1798

**Comment by hassaanCD** [comment]
Working fine on development

**Comment by hassaanCD** [comment]
Working fine on production
