### ISSUE TITLE
Setting up of theme (CSS file)

### ISSUE THREAD

**Issue by sunnyjindal** [the-canonizer/canonizer-3.0-frontend#1778]
Based on the designed component library ((https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=646-7262&t=6glvongkH8v0qnwQ-0)), we will create a master CSS file as per the ANT design requirement. This file will include the styles for the component library exclusively and will not contain any other styles.

Icon Library: https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=646-6831&t=6glvongkH8v0qnwQ-0

**Comment by ks-rahul** [comment]
I have set up the theme and have also created some components. There are some components left that will be made when a page is created.

**Comment by akashgit77** [comment]
working fine on the ux server

**Comment by akashgit77** [comment]
Working fine on the production
