### ISSUE TITLE
Home Page (Guest)

### ISSUE THREAD

**Issue by sunnyjindal** [the-canonizer/canonizer-3.0-frontend#1779]
Configure the template and new Home Page for guest users.
Figma Design links:
https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=3-1350&t=nn7Et438OEyiu9Cf-0

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Implemented on live
