### ISSUE TITLE
Home Page (Logged In)

### ISSUE THREAD

**Issue by sunnyjindal** [the-canonizer/canonizer-3.0-frontend#1780]
Home page when the user has logged into Canonizer.

Figma Link: https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=189-10773&t=nn7Et438OEyiu9Cf-0

**Comment by rupalichavan9860** [comment]
Implemented on live
