### ISSUE TITLE
Notification Dropdown

### ISSUE THREAD

**Issue by sunnyjindal** [the-canonizer/canonizer-3.0-frontend#1781]
Implementation of notification dropdown when the user clicks on bell icon in the header.

Figma Link: https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=77-4009&t=nn7Et438OEyiu9Cf-0

**Comment by saniatg** [comment]
Implemented on live
