### ISSUE TITLE
Previous Topic name is showing while loading of "Eventline"

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#1801]
When user click on "Eventline" button from tree of any topic, then it is showing some older topic while loading and also loading takes time. As shown in attached screenshot:

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/272984b2-fc97-4d1b-81a6-f46985b88e53)

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/1799664e-12af-4b6e-95ca-2f179ca997fc)

**Comment by DevAlchemyCD** [comment]
PR : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1808

**Comment by rupalichavan9860** [comment]
Working fine on development server

**Comment by hassaanCD** [comment]
Working fine on production
