### ISSUE TITLE
"Delegate your Support" button is showing in odd shape and style when user logged out from "Topic Detail" page

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#1802]
Steps:
Create a topic, User will be the camp leader in the agreement.
When on topic detail page, click on your profile and logout.
It shows delegate your support button in odd shape and style

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/bd3834ef-2a47-469f-938a-2f6d1789fa9d)

**Comment by DevAlchemyCD** [comment]
PR : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1816

**Comment by saniatg** [comment]
working fine on development

**Comment by hassaanCD** [comment]
Working fine on production
