### ISSUE TITLE
Sign Up/Registration Flow

### ISSUE THREAD

**Issue by sunnyjindal** [the-canonizer/canonizer-3.0-frontend#1823]
Complete Signup Flow

https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=31-17289&t=mWoF3Iu2sjcSSGae-0

For Preferred topics, we need to use the category API to list them down.

The user can skip or select one or more categories/topic and proceed ahead. The same will be stored in the database as user preference.

**Comment by rupalichavan9860** [comment]
Verified on live
