### ISSUE TITLE
Notification Screen

### ISSUE THREAD

**Issue by sunnyjindal** [the-canonizer/canonizer-3.0-frontend#1825]
https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=189-12137&t=TL58z9aWDRqaqd2g-0

We will need to create one APIs for deleting all notifications. This should have a prompt first and then delete action should be fired. Check reference: https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=1278-9724&t=TL58z9aWDRqaqd2g-0

For filter, we can have on page filter instead of API

**Comment by saniatg** [comment]
Functionality is implemented, issues are logged separately

**Comment by saniatg** [comment]
Functionality is implemented on live
