### ISSUE TITLE
Browse Canonizer Topics

### ISSUE THREAD

**Issue by sunnyjindal** [the-canonizer/canonizer-3.0-frontend#1826]
https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=3-1930&t=TL58z9aWDRqaqd2g-0

**Comment by DevAlchemyCD** [comment]
PR : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1855

**Comment by rupalichavan9860** [comment]
Verified on both UX and live
