### ISSUE TITLE
Camp Detail Screen

### ISSUE THREAD

**Issue by sunnyjindal** [the-canonizer/canonizer-3.0-frontend#1827]
We need to change the layout of the current camp detail screen.

Here are the Figma links for the camp detail page:
https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=193-28416&t=mWoF3Iu2sjcSSGae-0

Mobile Layout:
https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=776-14131&t=mWoF3Iu2sjcSSGae-0

Other Reference Screens

Refine Filter
https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=213-12084&t=mWoF3Iu2sjcSSGae-0

Active Filters
https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=193-28854&t=mWoF3Iu2sjcSSGae-0

Empty State: When no camp statement has been added
https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=202-3496&t=mWoF3Iu2sjcSSGae-0

Camp Details on Hover
https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=77-4580&t=mWoF3Iu2sjcSSGae-0

Statement added but not published
https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=203-4389&t=mWoF3Iu2sjcSSGae-0

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on live
