### ISSUE TITLE
Topic History

### ISSUE THREAD

**Issue by sunnyjindal** [the-canonizer/canonizer-3.0-frontend#1829]
Full set of screens:
https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=236-2583&t=TL58z9aWDRqaqd2g-0

**Comment by wahaj-hafeez** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1863

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1863

**Comment by saniatg** [comment]
implemented on ux-dev server, will log issues separately

**Comment by rupalichavan9860** [comment]
Pages are implemented on live , will log issues separately if any
