### ISSUE TITLE
Camp History

### ISSUE THREAD

**Issue by sunnyjindal** [the-canonizer/canonizer-3.0-frontend#1830]
Full set of screen:
https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=236-4243&t=TL58z9aWDRqaqd2g-0

**Comment by wahaj-hafeez** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1863

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1863

**Comment by akashgit77** [comment]
@wahaj-hafeez When we are going in "Camp History", then it is showing "Topic History".

https://github.com/user-attachments/assets/1bcdee49-3cf0-41b4-9294-f42443d8a295

**Comment by saniatg** [comment]
Verified on UX

**Comment by rupalichavan9860** [comment]
Pages are implemented on live , will log issues separately if any
