### ISSUE TITLE
Category List Screen

### ISSUE THREAD

**Issue by sunnyjindal** [the-canonizer/canonizer-3.0-frontend#1831]
https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=31-13575&t=TL58z9aWDRqaqd2g-0

**Comment by rupalichavan9860** [comment]
Below List of topics tags page is not available 

![image](https://github.com/user-attachments/assets/1022d1be-f541-4637-90fd-b427df7c2133)

**Comment by akashgit77** [comment]
Deployed on ux-server and working

**Comment by saniatg** [comment]
As mentioned above by Rupali one screen is missing apart from that functionality is implemented. Moving for now
