### ISSUE TITLE
Recent activity on home page ui and api integration.

### ISSUE THREAD

**Issue by ks-rahul** [the-canonizer/canonizer-3.0-frontend#1839]
https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=3-1350&t=vyBQZJiOlXgcn2jY-0

**Comment by rupalichavan9860** [comment]
Recent activities are available on home page

**Comment by rupalichavan9860** [comment]
Live - Recent activities are available on home page
