### ISSUE TITLE
Canonizer: Redirect user to the same page from where user has came to registration or login page

### ISSUE THREAD

**Issue by karun0607gautam** [the-canonizer/canonizer-3.0-frontend#1896]
As discussed the ask in this task is as:
1. Redirect the user to the same page after login or registration from where user is trying to perform the event of an authenticated user. 
For Example: If user is on sign petition page and click of signing the petition and is not authenticated . The application will ask him to login Or register , After successful login or registration redirect user back to sign petition page So that new user will not have to find the page again
2. In case of normal registration keep the functionality same to redirect user to account setting page

**Comment by akashgit77** [comment]
Working fine on ux server

**Comment by akashgit77** [comment]
Not working on production

**Comment by rupalichavan9860** [comment]
As it is not working on few pages I am reverting this . We will mention pages here

**Comment by ks-rahul** [comment]
@rupalichavan9860 Please specify the pages where this issue occurs.

**Comment by ks-rahul** [comment]
@akashgit77 @rupalichavan9860  this is working please recheck and let me know is its not.

**Comment by akashgit77** [comment]
@ks-rahul its not working with "Social Login".

**Comment by saniatg** [comment]
@ks-rahul this is not working on live

**Comment by ks-rahul** [comment]
@saniatg could you please specify the steps where it is not working? because I checked this on live with some of the pages and it is working

**Comment by saniatg** [comment]
@ks-rahul 

1. Go to topic detail page and logout then Login the user isn not redirected to detail page.
2. Video page
3. Upload file
4. Search page
5. History page
6. Threads
7. Account settings
8. Supported camps

**Comment by ks-rahul** [comment]
@saniatg This functionality has not been implemented like this. 


This functionality is implemented as follows:

When a user navigates to any page and clicks on the "Login" button, they are redirected back to the same page after successfully logging in.

**Comment by saniatg** [comment]
Working fine on live
