### ISSUE TITLE
Search Dropdown

### ISSUE THREAD

**Issue by sunnyjindal** [the-canonizer/canonizer-3.0-frontend#1897]
Please refer to:
https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=31-12732&t=PiuMViSMrX4jePdO-0

https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=31-13180&t=PiuMViSMrX4jePdO-0

**Comment by saniatg** [comment]
Functionality is implemeted on live
