### ISSUE TITLE
Search Result Page

### ISSUE THREAD

**Issue by sunnyjindal** [the-canonizer/canonizer-3.0-frontend#1898]
https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=123-18048&t=KeBn72FXu6MDzxIm-0

with advanced search: https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=3222-15571&t=KeBn72FXu6MDzxIm-0

Empty/No Result State: https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=2813-15773&t=KeBn72FXu6MDzxIm-0

**Comment by rupalichavan9860** [comment]
Verified on live
