### ISSUE TITLE
Create/Edit Topic

### ISSUE THREAD

**Issue by sunnyjindal** [the-canonizer/canonizer-3.0-frontend#1899]
https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=31-19911&t=KeBn72FXu6MDzxIm-0

https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=118-5436&t=KeBn72FXu6MDzxIm-0

https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=200-1598&t=KeBn72FXu6MDzxIm-0

https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=34-25525&t=KeBn72FXu6MDzxIm-0

The APIs for topic name are already done. Here is the ticket number: https://github.com/the-canonizer/canonizer-3.0-api/issues/1021

**Comment by rupalichavan9860** [comment]
Verified on UX and live
