### ISSUE TITLE
Camp Detail Page (after topic creation)

### ISSUE THREAD

**Issue by sunnyjindal** [the-canonizer/canonizer-3.0-frontend#1900]
https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=202-3496&t=KeBn72FXu6MDzxIm-0

https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=203-4232&t=KeBn72FXu6MDzxIm-0

**Comment by saniatg** [comment]
Functionality implemented on UX- server. Issues are logged separately

**Comment by rupalichavan9860** [comment]
Implemented on live
