### ISSUE TITLE
Add/Edit Statement with Preview

### ISSUE THREAD

**Issue by sunnyjindal** [the-canonizer/canonizer-3.0-frontend#1901]
Add/Edit Camp Statment
https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=51-28104&t=KeBn72FXu6MDzxIm-0

Preview
https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=247-6646&t=KeBn72FXu6MDzxIm-0

**Comment by saniatg** [comment]
Implemented on ux-server, issues are logged separately

**Comment by rupalichavan9860** [comment]
Implemented on live
