### ISSUE TITLE
Statement History

### ISSUE THREAD

**Issue by sunnyjindal** [the-canonizer/canonizer-3.0-frontend#1902]
All set of screens

https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=62-35086&t=KeBn72FXu6MDzxIm-0

**Comment by DevAlchemyCD** [comment]
PR :https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1918

**Comment by rupalichavan9860** [comment]
Page is implemented on live
