### ISSUE TITLE
Add Support

### ISSUE THREAD

**Issue by sunnyjindal** [the-canonizer/canonizer-3.0-frontend#1906]
Support Parent Camp
https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=282-16500&t=KeBn72FXu6MDzxIm-0

Support Child L0 Camp
https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=282-16503&t=KeBn72FXu6MDzxIm-0

Support Child L1 Camp
https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=282-16506&t=KeBn72FXu6MDzxIm-0

Support Parent Camp Again
https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=282-16510&t=KeBn72FXu6MDzxIm-0

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1978

**Comment by rupalichavan9860** [comment]
Page is implemented on live
