### ISSUE TITLE
Remove Support

### ISSUE THREAD

**Issue by sunnyjindal** [the-canonizer/canonizer-3.0-frontend#1907]
https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=282-16522&t=KeBn72FXu6MDzxIm-0

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1978

**Comment by rupalichavan9860** [comment]
Page is implemented on live
