### ISSUE TITLE
Browse Page is not working.

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/canonizer-3.0-frontend#1940]
Steps: 

1. Go to the url "https://ux-dev.canonizer.com/".
2. Then click on "Browse" from "Header" and "Footer" both navigation bar.

![Image](https://github.com/user-attachments/assets/8ff0f541-6be9-482c-ae6a-eecea9503ba6)

**Comment by sunnyjindal** [comment]
@akashgit77 check this again and if resolved, please mark it closed.

**Comment by akashgit77** [comment]
@sunnyjindal Working fine now
