### ISSUE TITLE
Back button at login page  is not working in certain scenario.

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/canonizer-3.0-frontend#1943]
Steps:

1.Click on "Start new topic" when we are not logged in.Then we will be landed at login page.

2. Then Click on the "Back" button.its not going back.

https://github.com/user-attachments/assets/af643eac-9502-465f-8d15-1e500146287a

**Comment by ks-rahul** [comment]
@akashgit77 In this case, when you press 'Back', it leads to the 'Create Topic' page. However, since you are not logged in, it will redirect you to the login page, which is the expected behavior.

**Comment by akashgit77** [comment]
@ks-rahul working fine now

**Comment by saniatg** [comment]
verified on live
