### ISSUE TITLE
Register button is not working in mobile view, when we are going from "Three Bar Option" button.

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/canonizer-3.0-frontend#1944]
Steps:

1. Go to the url "https://ux-dev.canonizer.com/" in Mobile browser.
2. Click on "Three Bar Option" and then click on "Register Button".

https://github.com/user-attachments/assets/f80156b2-a9f4-4ce3-9bbf-aed0e6b1fe9a

**Comment by ks-rahul** [comment]
@akashgit77 both buttons are working on the server.

**Comment by akashgit77** [comment]
@ks-rahul working fine now

**Comment by saniatg** [comment]
verified

**Comment by rupalichavan9860** [comment]
Verified on live
