### ISSUE TITLE
Profile Screen - Personal Info

### ISSUE THREAD

**Issue by sunnyjindal** [the-canonizer/canonizer-3.0-frontend#1953]
https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=4625-39796&t=rsLa6GzzVaIzQzMd-0

We have removed the mobile number verification from this as it was not being used as of now.

**Comment by rupalichavan9860** [comment]
Verified on live
