### ISSUE TITLE
Profile Screen - Supported Camps

### ISSUE THREAD

**Issue by sunnyjindal** [the-canonizer/canonizer-3.0-frontend#1954]
https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=4625-40725&t=rsLa6GzzVaIzQzMd-0

https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=4625-41384&t=rsLa6GzzVaIzQzMd-0

https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=4625-40897&t=rsLa6GzzVaIzQzMd-0

**Comment by rupalichavan9860** [comment]
Verified on live
