### ISSUE TITLE
Create/Edit Camp Screen

### ISSUE THREAD

**Issue by sunnyjindal** [the-canonizer/canonizer-3.0-frontend#1960]
https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=203-4523&t=rsLa6GzzVaIzQzMd-0

https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=226-3400&t=rsLa6GzzVaIzQzMd-0

https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=226-3665&t=rsLa6GzzVaIzQzMd-0

https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=226-3874&t=rsLa6GzzVaIzQzMd-0

https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=203-5171&t=rsLa6GzzVaIzQzMd-0

https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=226-4116&t=rsLa6GzzVaIzQzMd-0

**Comment by rupalichavan9860** [comment]
Screens are available on live
