### ISSUE TITLE
Camp Leader Functionality

### ISSUE THREAD

**Issue by sunnyjindal** [the-canonizer/canonizer-3.0-frontend#1962]
Figma design for camp leader:
https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=4918-25564&t=LxpN63PsBvJlXEfC-4

**Comment by M-Darab** [comment]
Figma design for camp leader:
https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=4918-25564&t=LxpN63PsBvJlXEfC-4

**Comment by sajid315** [comment]
@wahaj-hafeez for sign petition API, response messages are updated under following PR.

https://github.com/the-canonizer/canonizer-3.0-api/pull/1125

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2039

**Comment by rupalichavan9860** [comment]
Functionality is available on live
