### ISSUE TITLE
Delete Comment

### ISSUE THREAD

**Issue by sunnyjindal** [the-canonizer/canonizer-3.0-frontend#1967]
https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=4639-23912&t=rsLa6GzzVaIzQzMd-0

**Comment by saniatg** [comment]
@ks-rahul 
https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/issues/1120
related issue

**Comment by rupalichavan9860** [comment]
Verified on live
