### ISSUE TITLE
After clicking "Join Canonizer to Support" button status is not changing.

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/canonizer-3.0-frontend#1971]
https://github.com/user-attachments/assets/72aa6831-5e3c-4d25-bd3b-061e97481975

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2314

**Comment by saniatg** [comment]
working fine now on ux-dev

**Comment by hassaanCD** [comment]
Verified on live
