### ISSUE TITLE
At the topic history page it should be "TOPIC HISTORY BASED ON STATUS"  instead of "TOPIC BASED ON STATUS".

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/canonizer-3.0-frontend#1984]
1. It should be "TOPIC HISTORY BASED ON STATUS" instead of "TOPIC BASED ON STATUS"
2. Also it should be "view this version" instead of "view version".

![Image](https://github.com/user-attachments/assets/109b0a0c-ec26-4245-b1f1-311f8443f41e)

 
![Image](https://github.com/user-attachments/assets/0f4b3b72-2048-4968-bcba-f9214522e4bb)

**Comment by saniatg** [comment]
verified on dev

**Comment by hassaanCD** [comment]
Verified on live

**Comment by saniatg** [comment]
@ks-rahul  @nd point is not fixed on dev -Also it should be "view this version" instead of "view version".

**Comment by ks-rahul** [comment]
@saniatg history page labels are working fine on both servers. I am attaching the screenshot below. please check once again.

this ux-ui dev server
![Image](https://github.com/user-attachments/assets/e973160b-b5a0-4cd1-9a94-96cb40f6756f)

![Image](https://github.com/user-attachments/assets/149771bf-7db6-47ca-8431-7ca2dc369ac8)

![Image](https://github.com/user-attachments/assets/d7762af9-4b77-4799-a35a-aeca8cf2c3fe)


this is from the live server
![Image](https://github.com/user-attachments/assets/9666e437-ae17-4c1d-829c-d731f3d4b53f)

![Image](https://github.com/user-attachments/assets/c3a4db1b-8244-4bd4-a06a-a9fa759baaa9)

![Image](https://github.com/user-attachments/assets/a1d6d7ea-9bd0-4489-9da0-33125ef81780)

**Comment by rupalichavan9860** [comment]
Yes . Working fine on both UX and live server
