### ISSUE TITLE
After creating statement it is showing "no data" then actual data appears.

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/canonizer-3.0-frontend#1990]
https://github.com/user-attachments/assets/a4ac9af4-70fc-4810-8ce2-13c8e5756513

**Comment by sajid315** [comment]
@akashgit77 I just checked this issue , API is returning data successfully (in milliseconds) but until the API response there is a glitch coming on. 
And might be we need to add skeleton here for history pages.

@wahaj-hafeez please look into this.

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2080/files

**Comment by saniatg** [comment]
Verified

**Comment by saniatg** [comment]
Working fine on live
