### ISSUE TITLE
"Manage Statement" button is not working at "Camp update page".

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/canonizer-3.0-frontend#1997]
https://github.com/user-attachments/assets/8d88ceb4-758d-4e65-8d63-f16f44d72e17

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2314

**Comment by saniatg** [comment]
The button is not there now

**Comment by hassaanCD** [comment]
"Manage Statement" button is removed from "Update Camp" page
