### ISSUE TITLE
Multiple supports are added when we are clicking multiple times at "add support" button.

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/canonizer-3.0-frontend#2010]
![Image](https://github.com/user-attachments/assets/bc50d21f-2514-42e3-b795-07452f2f047f)

**Comment by DevAlchemyCD** [comment]
This issue is fixed and code is merged on UX-dev. Now its working fine on UX-dev

**Comment by saniatg** [comment]
verified

**Comment by rupalichavan9860** [comment]
Verified on live
