### ISSUE TITLE
Some features in "Statement Editor" is not working

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#2017]
Some features of "Statement Editor" are not working like "numbering", "bullet points", upload image link.
As shown in attached screenshots:

![Image](https://github.com/user-attachments/assets/3a6ae040-3d05-48cc-85ed-23b5db072937)

![Image](https://github.com/user-attachments/assets/938334eb-8bfe-4dce-bd3e-2cd82e61e9eb)

**Comment by hassaanCD** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on live
