### ISSUE TITLE
Update Comparison Changes UI in mobile screen

### ISSUE THREAD

**Issue by sajid315** [the-canonizer/canonizer-3.0-frontend#2024]
As direction by @sunnyjindal , figma updated the comparison pages for mobile view and changed the UI to tabs. Following is the node id.

https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=4479-28887&t=EYe8i1x8u4rHd1iy-0

Also we need to address reading point of user while navigating b/w the tabs.

**Comment by DevAlchemyCD** [comment]
PR: PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2039

**Comment by rupalichavan9860** [comment]
Verified on both UX and live
