### ISSUE TITLE
The "navigation back" functionality of the video page is not working properly

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#2041]
Steps:
User opens "videos" page and 
Then user clicks on 1st, 2nd and 3rd video turn by turn
Now user clicks on back button (on 3rd video)
First it navigates to 2nd video, user again clicks on back button, now it navigates to 1st video (introduction)
When user clicks back here on 1st video, it stays there and navigate to home page after several clicks

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2314

**Comment by hassaanCD** [comment]
Verified on UX-DEV

**Comment by hassaanCD** [comment]
Verified on live
