### ISSUE TITLE
Not able to change default algorithm (one person one vote) on home page (after page refresh)

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#2042]
Steps:
Login and select some other algorithm other than default “One person One Vote” like “Mind Expert” on home page
Then even refresh the home page or navigate to any other page and then navigate back to home page
Your can see default algorithm “One person One Vote” again instead of previously selected “Mind Expert”

**Comment by ks-rahul** [comment]
@hassaanCD This is implemented like this. we are not keeping value preserved.

**Comment by hassaanCD** [comment]
Verified

**Comment by hassaanCD** [comment]
I am closing this ticket as this feature (algorithm dropdown) from home page is now removed from new design.
