### ISSUE TITLE
Home page: “List of Topic Tags” navigation show no data

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#2043]
Steps:
Login and click on "See more" in "List of Topic Tags" section
Click on any topic 
It will navigate you to a page with no data and only you see is "Topics by cats"

**Comment by sajid315** [comment]
@ks-rahul for this page we can use the same API as we have in browse page. Only the difference will be passing one unique tag_id by getting from URL. 

```
{
    "algorithm": "blind_popularity",
    "asofdate": 1724637183.307,
    "namespace_id": "",
    "page_number": 1,
    "page_size": 24,
    "search": "",
    "filter": 0,
    "asof": "review",
    "user_email": "",
    "is_archive": 0,
    "sort": false,
    "page": "browse",
    "topic_tags": [5]   // this  should be array of tag id's
}
```

**Comment by hassaanCD** [comment]
Verified

**Comment by rupalichavan9860** [comment]
The List of Topic Tags section has been deleted from the home page.
