### ISSUE TITLE
Not able to navigate to "home page" when first click “on Canonizer” logo

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#2044]
User not able to navigate to "Home Page" on Canonizer” logo first click

**Comment by ks-rahul** [comment]
@hassaanCD This is working fine but it takes some time to navigate. If there is a specific scenario, please provide it.

**Comment by ks-rahul** [comment]
@hassaanCD i have checked this again. this is working fine please check once

**Comment by hassaanCD** [comment]
Verified

**Comment by hassaanCD** [comment]
Verified on live
