### ISSUE TITLE
When user "Disable" notifications from dropdown, it remain "Enable", on notification page

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#2046]
Steps:
User Login and clicks on notification dropdown from header on right corner
Now user clicks on "View All" option in dropdown
It will navigate to "Notification" page
Now open "Notification" dropdown and "disable" push notification
Observe "push notification" on notification page
It remained "Enabled"

Expected Result: "Push notification" on notification page must be "Enabled" when user enabled it from dropdown

**Comment by akuks** [comment]
@hassaanCD Whats the PR Number?

**Comment by ks-rahul** [comment]
> @hassaanCD Whats the PR Number?

https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2323

**Comment by hassaanCD** [comment]
Verified

**Comment by hassaanCD** [comment]
Verified on live
