### ISSUE TITLE
Eventline BreadCrumb must be consistent and populated with data

### ISSUE THREAD

**Issue by sajid315** [the-canonizer/canonizer-3.0-frontend#2049]
Found some issue on eventline bread crumb, it should be clickable as in topic detail page and must show the data. 
Following is the source of issue.

![Image](https://github.com/user-attachments/assets/0b76a4a7-b21a-4cf9-90b6-4b5a5d159fab)

**Comment by hassaanCD** [comment]
Eventline tool tip must appear under the text.


![Image](https://github.com/user-attachments/assets/19305e68-281a-4922-8639-d5db9aa17748)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2080/files

**Comment by hassaanCD** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on live
