### ISSUE TITLE
Make the reason on the Support popup to be Optional

### ISSUE THREAD

**Issue by rohit-talentelgia** [the-canonizer/canonizer-3.0-frontend#2051]
The points need to be implemented:

1 Add "(Optional)" before "Reason for adding support" as below

(Optional) Reason for adding support

2. Move the Nickname selection before the "Reason for adding support" option as below:

![image](https://github.com/user-attachments/assets/2a2e8d66-41e8-4417-9b46-8b27a22b238d)

**Comment by rohit-talentelgia** [comment]
@wahaj-hafeez I assigned this to Vikas as he is already working on support ticket and this can be covered with same

**Comment by saniatg** [comment]
verified

**Comment by saniatg** [comment]
Verified on live
