### ISSUE TITLE
Add/Improve Eventline page skeleton while loading

### ISSUE THREAD

**Issue by sajid315** [the-canonizer/canonizer-3.0-frontend#2057]
@wahaj-hafeez we need to handle skeleton for eventline page for the following sections,
1- Events section.
2- Animation play/pause section.
3- Animation area skeleton.

**Comment by DevAlchemyCD** [comment]
PR:  https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2080/files

**Comment by saniatg** [comment]
verified

**Comment by saniatg** [comment]
working fine on live
