### ISSUE TITLE
"Create topic" button is not enabled on default canon (General)

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#2060]
When user logged in and try to create a topic with default canon (General), then "create topic" button remains disabled unless user select any cannon from drop down list.

**Comment by ks-rahul** [comment]
@hassaanCD This is working fine. If there is a specific scenario, please provide it.

**Comment by hassaanCD** [comment]
Yes @ks-rahul , the scenario is:
1- Open the site in private window. 
2- Login into site, and then click on start a topic. 
3- After that I just added this text "Zeew" in topic name. In this case button is disabled still.

![Image](https://github.com/user-attachments/assets/faa6bad7-63d5-49db-9120-410b6205401c)

**Comment by hassaanCD** [comment]
Not fixed

**Comment by rupalichavan9860** [comment]
Verified on live
