### ISSUE TITLE
Pagination dropdown issue

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#2068]
When user logged in, 
navigate to browse page,
and scroll down, 
there are 3 options in pagination dropdown,
10, 16 and 24
When user select 24 at first, it shows 24 Topics in result
When user select 16 or 10, and again open dropdown
24 is missing
As shown in attached screenshot:

![Image](https://github.com/user-attachments/assets/29a97b6d-51ec-417d-83df-cd11c59cbeb5)

![Image](https://github.com/user-attachments/assets/3c37df35-e989-4bfc-9895-b494d1119499)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2123

**Comment by hassaanCD** [comment]
Verified

**Comment by hassaanCD** [comment]
Verified on live
