### ISSUE TITLE
"Manage camp" button is not showing in "create new camp" agreement tooltip

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#2076]
"Manage camp" button is not showing in "create new camp" agreement tooltip.

![Image](https://github.com/user-attachments/assets/22976b96-ae57-4ae0-8011-f79f823653c8)

Like it is showing in "Topic Detail" page.

![Image](https://github.com/user-attachments/assets/491c8934-bfc7-4656-b2fd-cfec72196e20)

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on live
