### ISSUE TITLE
Updates in submit support for optional and require fields .

### ISSUE THREAD

**Issue by gautamv16** [the-canonizer/canonizer-3.0-frontend#2078]
1.	In camp statement there is a popup to manage support where make reason field optional and add (optional ) In the label. 

2.	At the same page there a option for nickname . Which is optional as of now . It should be compulsory .If somebody want to add the support nickname should be compulsory i.e. nickname* 
![Screenshot 2024-08-23 144613](https://github.com/user-attachments/assets/602098c3-1562-45fd-9b4f-fe43e682f7df)

**Comment by gautamv16** [comment]
Its not done . Place compulsory (*) in front of nickname and add (optional)  at the end of label

**Comment by rupalichavan9860** [comment]
Not working

**Comment by saniatg** [comment]
verified on ux-server

**Comment by saniatg** [comment]
Working fine on live
