### ISSUE TITLE
Additional information address update missing address 1 and address 2 field .

### ISSUE THREAD

**Issue by gautamv16** [the-canonizer/canonizer-3.0-frontend#2079]
There no filed available to update address . Please refer attach screenshot of canonizer -3.0.

![address ](https://github.com/user-attachments/assets/4f13a808-21a9-41bc-a2c5-008daeae87b8)

**Comment by rupalichavan9860** [comment]
Yes . Unable to change the address

**Comment by gautamv16** [comment]
1 . Address update is not loading google location Api .
2 . Zip code must not accept only 000000  and zip code length limit max 10 digit . 
3 . Address  must not accept only special character it  must contain combination of digit and special character .
![address update](https://github.com/user-attachments/assets/abbdf8d2-21db-4527-9d36-ab9d28837763)

**Comment by gautamv16** [comment]
![address special](https://github.com/user-attachments/assets/f49ad1c6-3297-476c-83d3-0076371e96d4)

**Comment by gautamv16** [comment]
@vikasranatalentelgia none of above mentioned issues are done on ux-dev server. Just verified. Please have a look again.
![desk1](https://github.com/user-attachments/assets/b299edd6-4d49-48d5-a290-6622e7996683)

**Comment by rupalichavan9860** [comment]
Verified on UX server

**Comment by rupalichavan9860** [comment]
Verified on live
