### ISSUE TITLE
Nickname section header public and private .

### ISSUE THREAD

**Issue by gautamv16** [the-canonizer/canonizer-3.0-frontend#2081]
1. There must be a label of visibility status in header .
2. There must be a hover text  with  public and private icon .
Refer screenshot
![status](https://github.com/user-attachments/assets/7c5b2e2e-c509-4a28-82d8-00373fb5998e)

**Comment by saniatg** [comment]
verified and is working fine

**Comment by gautamv16** [comment]
Verified
