### ISSUE TITLE
Preferences are not getting saved

### ISSUE THREAD

**Issue by gautamv16** [the-canonizer/canonizer-3.0-frontend#2093]
When we are saving preference language, algorithm ,topic tags all are not getting saved and pre populated after saved.
![prefrences](https://github.com/user-attachments/assets/18f61125-2d7e-45c0-9659-91a2b5441251)

**Comment by rupalichavan9860** [comment]
@gautamv16 Yes this is already reported in https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/issues/1128

**Comment by gautamv16** [comment]
Ok duplicated. Closing it
