### ISSUE TITLE
Make browse search like type-ahead as we have in old system

### ISSUE THREAD

**Issue by sajid315** [the-canonizer/canonizer-3.0-frontend#2099]
1- Implement search type-ahead in broswe page same like older one.

![Image](https://github.com/user-attachments/assets/1ffd7e9a-4d84-4be0-b496-7b7a41ab2c8d)

2- Also implement the copy icon and functionality for card by collaborate with Rahul.
3- Also we need to update the text for filter tags dropdown "info" icon. 

![image](https://github.com/user-attachments/assets/c7c036d1-4e35-418e-b764-1eb706d406aa)

**Comment by sajid315** [comment]
@wahaj-hafeez following is the message provided by Twinkle to insert at info icon "pop-over" for topic tags dropdown.

```
Topic Tags are keywords that help categorize and organize topics on Canonizer. 
By adding relevant tags to a topic, users can enhance discover-ability, making it easier for others to find and engage with topics that match their interests.
```

**Comment by sajid315** [comment]
@wahaj-hafeez as per discussion with Rahul we need to add copy icon for cards of browse page results. 

Also for topic tags listing I provided the payload param for sorting by title, so in the dropdowns the payload should be like below.

```
{
    "search_term": "",
    "sort_by": "asc"
}
```

**Comment by wahaj-hafeez** [comment]
PR:  https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2111

**Comment by wahaj-hafeez** [comment]
PR:  https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2111

**Comment by DevAlchemyCD** [comment]
PR:  https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2111

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
verified on live
