### ISSUE TITLE
Fix History page UI in case of large text on mobile view

### ISSUE THREAD

**Issue by sajid315** [the-canonizer/canonizer-3.0-frontend#2119]
We should fix the UI in case of larger text for camp/topic names OR summary field etc.

![Image](https://github.com/user-attachments/assets/03633410-cde4-43a5-94c2-44566d1a69d4)

**Comment by rupalichavan9860** [comment]
Not fixed for camp name 
![image](https://github.com/user-attachments/assets/db654f71-a47f-4dc2-80e9-a798eed43b9e)

**Comment by rupalichavan9860** [comment]
Verified on UX server

**Comment by rupalichavan9860** [comment]
Verified on live
