### ISSUE TITLE
Need to sync the breadcrumb for history pages

### ISSUE THREAD

**Issue by sajid315** [the-canonizer/canonizer-3.0-frontend#2126]
We need to make the breadcrumb same on history pages , as we are showing on topic detail page and other pages. 

Right now we are showing like this, 

![Image](https://github.com/user-attachments/assets/23ce6da2-5b10-4dce-9b1d-2f75c34970f7)

It should be like this, 

![Image](https://github.com/user-attachments/assets/1f5fdd28-c18e-44c0-95de-a273490153d6)

**Comment by sajid315** [comment]
During testing by Rupali, there's an issue coming during page load. The breadcrumb appears after a second, might be due to a glitch.
We need to check this issue or we must show the skeleton in case of data loading.

![Image](https://github.com/user-attachments/assets/f0f34664-007b-468e-ba62-e8f7bb0ae45d)

**Comment by DevAlchemyCD** [comment]
As per the new Figma, we updated the breadcrumb on UX-dev server.

**Comment by rupalichavan9860** [comment]
Verified on both UX and live
