### ISSUE TITLE
Remove Trending Topics from homepage

### ISSUE THREAD

**Issue by rohit-talentelgia** [the-canonizer/canonizer-3.0-frontend#2128]
As discussed with Brent, the below changes are required on the homepage:

1. Remove the "Trending Topics" section from the homepage.
2. Move "WHAT’S NEW AT CANONIZER?" in place of "Trending Topics"
3. Move "Recent Activities" under "WHAT’S NEW AT CANONIZER?"

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on live
