### ISSUE TITLE
Add "Browse all" button on homepage

### ISSUE THREAD

**Issue by sajid315** [the-canonizer/canonizer-3.0-frontend#2134]
As discussed in morning scrum call of 5 Sep, we need to add the "Browse All" button for user and redirect it to the browse page. 
This button will be implemented due to removal of trending topics on homepage.
Goal is to provide a new interaction point for browse page when user visits.

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on live
