### ISSUE TITLE
Re-Verify Or Upgrade Cache Refresh on build/deployment

### ISSUE THREAD

**Issue by sajid315** [the-canonizer/canonizer-3.0-frontend#2196]
On each deployment/build from front-end side, users having problems about cache to use the new released effects.

Right now we are having script that is working after each build at front-end , but its having problem with automatic CI/CD flow. 
Also its clearing cookies of users that is wrong.

We need to recheck or should upgrade to a more concise solution for clearing cache without logout of users from site.

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2203

**Comment by sajid315** [comment]
Each time when build is creating on ux-dev server the cache clear is working as expected. And build number getting updated.
Cache clearing the following right now:
Local Storage (auth_token key), Cookies getting cleared and browser cache getting cleared.
