### ISSUE TITLE
Browse Page: Need to handle copy icon

### ISSUE THREAD

**Issue by sajid315** [the-canonizer/canonizer-3.0-frontend#2201]
As discussed with Twinkle , we need to handle copy icon on hover. 
Copy icon will copy the text of topic and icon should be grey same as we have the color of views icon.

![Image](https://github.com/user-attachments/assets/5133b99e-24fd-4a82-bba0-10ccdf321432)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2203

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on live
