### ISSUE TITLE
Browse Page showing one record for a sec

### ISSUE THREAD

**Issue by sajid315** [the-canonizer/canonizer-3.0-frontend#2210]
Navigation to "Browse" page showing a single record for a second, then reloads to actual results. 
Following is the screenshot of glitch coming at first reload, mostly after clearing cache. 

![Image](https://github.com/user-attachments/assets/bd3f644b-140a-42a7-8ecb-9c36d8edc699)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2212

**Comment by saniatg** [comment]
@sajid315 , this is not fixed. Now it shows blank page and then reloads the result instead there should be a loader

**Comment by DevAlchemyCD** [comment]
deployed on ux-dev server, we implemented Skelton for on-page load.

**Comment by saniatg** [comment]
Verified on UX

**Comment by saniatg** [comment]
verified on live
