### ISSUE TITLE
AgreeToChange Api must be called one time, also update the popup of alert

### ISSUE THREAD

**Issue by sajid315** [the-canonizer/canonizer-3.0-frontend#2211]
We need to check the agree to change api call for topic/camp/statement, following are the issues right now on ux-dev.

1- User is able to click multiple time on "Agree Check Box" and api call is going on multiple times.
2- Alert pop should be updated as per new standard alert provided in figma rather than centered alert box.

![Image](https://github.com/user-attachments/assets/69190249-4a40-4782-956c-7547fc9eaa8a)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2212

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on live
