### ISSUE TITLE
Homepage first section new UI

### ISSUE THREAD

**Issue by ks-rahul** [the-canonizer/canonizer-3.0-frontend#2217]
https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=0-1&node-type=canvas&t=zdUVmry4DctV3Q9s-0

https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=0-1&node-type=canvas&t=zdUVmry4DctV3Q9s-0

**Comment by rupalichavan9860** [comment]
Implemented

**Comment by rupalichavan9860** [comment]
Implemented on live
