### ISSUE TITLE
Records duplicating at the end of pagination

### ISSUE THREAD

**Issue by sajid315** [the-canonizer/canonizer-3.0-frontend#2219]
In the history pages while scrolling the page , records are duplicating at the end of pagination. 

Here in below example total records are 6, but its showing 8 records. 
https://ux-dev.canonizer.com/topic/history/5754-checkloading-issue12133

![Image](https://github.com/user-attachments/assets/8503712a-b187-44ad-b5bc-c3cec848e7a5)

**Comment by saniatg** [comment]
verified

**Comment by hassaanCD** [comment]
Verified on live
