### ISSUE TITLE
Handle/Refresh Cache of Browsers on build deployment

### ISSUE THREAD

**Issue by sajid315** [the-canonizer/canonizer-3.0-frontend#2254]
In this issue we need to handle/refresh cache of users browser and have to refresh it on build deployment. 
All code effects must be rendered after cache clear.

**Comment by DevAlchemyCD** [comment]
I reviewed the code for clearing the cache and found that it is commented in the root file (i.e., App. TSX). I uncommented the code and raised a PR for UI-UX-Overhaul. 

PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2250

**Comment by DevAlchemyCD** [comment]
I have cleared the local storage and cookies when the build number is updated.
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/2258
