### ISSUE TITLE
Refine Filter issue

### ISSUE THREAD

**Issue by vikasranatalentelgia** [the-canonizer/canonizer-3.0-frontend#2299]
![Image](https://github.com/user-attachments/assets/f897b59e-1a1b-4155-80b3-7b4882dd0ada)
![Image](https://github.com/user-attachments/assets/9fb467e4-95e8-4206-b7c3-c4c935358ee3)

No API calls when clearing filter

**Comment by saniatg** [comment]
Working fine on development, tested with Vikas and Abhi

**Comment by saniatg** [comment]
Working fine on production
