### ISSUE TITLE
The user is not able to zoom-in, zoom-out the images (Topic & Camp details) while browsing the site on Android device.

### ISSUE THREAD

**Issue by ashish76** [the-canonizer/canonizer-3.0-frontend#2308]
If the users browse the Canonizer website on their Android device then they cannot able to use the zoom-in and zoom-out features on the images (Ref. Topic / Camp details page). Whereas the iOS device allows this feature.

We have to find a similar solution for Android users as well.

**Comment by rupalichavan9860** [comment]
Verified on UX server

**Comment by rupalichavan9860** [comment]
Verified on live
