### ISSUE TITLE
Issues while Removing support during Add to another camp

### ISSUE THREAD

**Issue by sajid315** [the-canonizer/canonizer-3.0-frontend#2315]
Following are the cases needed to be checked.

1. Create a topic, by default support is in Agreement camp.
2. Create C1 and open pop up of Add Support. Select the Remove All Support checkbox here.
3. Following attached is the current output we have. Results should be as expected below.

Expected Results: This should only remove support from Agreement Camp and Add in C1 with proper messages.

![Image](https://github.com/user-attachments/assets/0b418164-45e0-4002-946a-60931eb51d38)

1. Create the sibling of C1 named as C2. 
2. Now while adding support in C2 , when user will click the "Remove all support". It disabled the both (C1 & C2) drag handles and on click of submission messages are wrong.
3. Following attached is the current output we have. Results should be as expected below.

Expected Results: This should only remove support from the other camps except in which we are adding the support with proper messages.
 
![Image](https://github.com/user-attachments/assets/1068f1ad-de01-4126-9158-35911ffcdf83)

**Comment by saniatg** [comment]
working fine on dev

**Comment by rupalichavan9860** [comment]
Verified on live
