### ISSUE TITLE
When the notification toggle is off still receive the notification which is incorrect

### ISSUE THREAD

**Issue by ks-rahul** [the-canonizer/canonizer-3.0-frontend#2322]
When the notification toggle is off still receive the incorrect notification

**Comment by ashish76** [comment]
Hi @saniatg 
We have verified this on production and local environment and it is working fine. In the UX-Dev server, we are not getting any notification so we didn't test it there. Just to inform you that toggling the notification button will enable/disable the push notification popup. If you disable it the push notification will not come but still, you will be able to see the notification on the list. If this is not the case I would request you to elaborate the steps to reproduce it.

**Comment by saniatg** [comment]
Okay @ashish76 , then it is working fine
