### ISSUE TITLE
Remove extra API call

### ISSUE THREAD

**Issue by shahab-ramzan** [the-canonizer/canonizer-3.0-frontend#557]
We don't need edit-camp-statement API call on the creation of a Statement.

**Comment by shahab-ramzan** [comment]
Raised PR https://github.com/the-canonizer/canonizer-3.0-frontend/pull/561

**Comment by rupalichavan9860** [comment]
Verified by Ashutosh

**Comment by subhancd** [comment]
verified on dev

**Comment by subhancd** [comment]
verified on development server

**Comment by hassaanCD** [comment]
Verified on production
