### ISSUE TITLE
Hide Social Icons

### ISSUE THREAD

**Issue by shahab-ramzan** [the-canonizer/canonizer-3.0-frontend#558]
As of now, we don't have social media accounts so we need to hide these icons.
We will show these icons later 

![Image](https://user-images.githubusercontent.com/96526562/203754885-7c214e0d-7f29-47ef-a4e4-a1d3dc8117f3.png)

**Comment by shahab-ramzan** [comment]
Raised PR https://github.com/the-canonizer/canonizer-3.0-frontend/pull/559

**Comment by subhancd** [comment]
working fine on both staging and beta. @rupalichavan9860
