### ISSUE TITLE
Turn off media uploading of files in 3.0 and we will use WikiMedia to upload files

### ISSUE THREAD

**Issue by shahab-ramzan** [the-canonizer/canonizer-3.0-frontend#574]
We will run into many problems, especially copyright problems, which must be resolved at some time.  I’m thinking before we turn it on.

Also, people could upload too much stuff, canonizer hosting it all for free, costing us too much money, especially for large files.

Could we just point people to [Wikipedia's File upload wizard](https://en.wikipedia.org/wiki/Wikipedia:File_Upload_Wizard) in all the help files and messages.  Providing a code snippet of how to include a wikimedia file, instead of a file served from canonizer.

Leave the 3.0 upload file code in place, only usable by admin.  We could decide to turn it on for everyone in the future, once copyright issues prevention design has been achieved and implemented

From Jira:
https://canonizer.atlassian.net/browse/CAN-1272

**Comment by cd-ali-ehsan** [comment]
This is completed.
