### ISSUE TITLE
Email Address Verification on Sign up

### ISSUE THREAD

**Issue by shahab-ramzan** [the-canonizer/canonizer-3.0-frontend#575]

**Comment by ashish76** [comment]
@shahab-ramzan: What to do with this ticket, please provide more details.

As per the current flow: On submission of the registration form, a notification email goes to the user with an OTP.  A user enters the OTP and redirects to the dashboard on successful verification and a welcome email goes to the user.

**Comment by shahab-ramzan** [comment]
@ashish76 I just checked, there's no issue right now. So we can close this ticket
