### ISSUE TITLE
Make it easier to find parent camps on the camp edit form page

### ISSUE THREAD

**Issue by shahab-ramzan** [the-canonizer/canonizer-3.0-frontend#577]
Currently the choices in the parent camp drop down for the edit camp form:
https://canonizer.com/manage/camp/1873
are very hard to find, when the list is long.
There should be some way to show the current tree structure, possibly with indentation of camps, under parent camps, according to the current canonized tree/one person one vote. If that doesn't fit on a page, then at least sort the list, alphabetically.

refer 2.0 ticket for more details  : 

https://github.com/the-canonizer/canonizer.2.0/issues/1147

From jira:
https://canonizer.atlassian.net/browse/CAN-854

**Comment by rupalichavan9860** [comment]
Search is already implemented. We just need to sort the list alphabetically as mentioned in 2.0 ticket

**Comment by rupalichavan9860** [comment]
Verified
