### ISSUE TITLE
This Route should be private (https://canonizer3.canonizer.com/reset-password)

### ISSUE THREAD

**Issue by shahab-ramzan** [the-canonizer/canonizer-3.0-frontend#583]
1. Go to https://canonizer3.canonizer.com
2. Log Out user 
3. Go to https://canonizer3.canonizer.com/reset-password

Reset Password Page shouldn't be open for logged out user

![Image](https://user-images.githubusercontent.com/96526562/204301886-6c9b9670-2eee-4190-8805-71b78a88723b.png)

**Comment by subhancd** [comment]
not working on both staging and beta. @shahab-ramzan kindly, check

![Image](https://user-images.githubusercontent.com/104552751/204725642-0e8ca436-e51c-4aed-9a7f-0e53ccd689ac.png)

**Comment by subhancd** [comment]
working fine on both staging and beta. @rupalichavan9860

**Comment by rupalichavan9860** [comment]
Verified on live
