### ISSUE TITLE
Hide Upload Files option in Beta.

### ISSUE THREAD

**Issue by rohit-talentelgia** [the-canonizer/canonizer-3.0-frontend#604]
Hide the option of Upload file from the header in beta.canonizer.com. It will only be visible to the admin user.

**Comment by rupalichavan9860** [comment]
@vikasranatalentelgia , File upload page is visible to non admin user with below steps : 
1. Copy URL https://beta.canonizer.com/uploadFile
2. Login with non admin user

Actual Result : It is showing file upload page and user is able to upload the file

**Comment by rupalichavan9860** [comment]
Working fine now
