### ISSUE TITLE
Emails : Hide Social Icons 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer-3.0-frontend#605]
Ref ticket : https://github.com/the-canonizer/canonizer-3.0-frontend/issues/558

**Comment by sajid315** [comment]
Changes pushed from back end, PR has been raised.

**Comment by subhancd** [comment]
the icons are still there in the mails
![Image](https://user-images.githubusercontent.com/104552751/205835593-f684ed8e-4f6b-464e-9be8-49bff55192fc.png)

**Comment by sajid315** [comment]
@subhancd now these also fixed on staging.


![Image](https://user-images.githubusercontent.com/111273633/205849186-fb0ded6b-b1ed-4a1e-912a-c0b29e5d3453.png)

**Comment by rupalichavan9860** [comment]
Verified
