### ISSUE TITLE
Hide message from beta.canonizer.com

### ISSUE THREAD

**Issue by rohit-talentelgia** [the-canonizer/canonizer-3.0-frontend#608]
Implement check on beta.canonizer.com to hide below message:

This is not the live system. Any data submitted here is for testing purposes only and will be lost. Please go to canonizer.com

**Comment by rupalichavan9860** [comment]
@vikasranatalentelgia The message has been removed from both beta.canonizer.com and canonizer3.canonizer.com as of now.

**Comment by ks-rahul** [comment]
@vikasranatalentelgia for hiding the disclaimer you just need to update the env file.

NEXT_PUBLIC_HIDE_DISCLAIMER=true
