### ISSUE TITLE
Beta Ad Unit Code Update

### ISSUE THREAD

**Issue by gautamv16** [the-canonizer/canonizer-3.0-frontend#610]
Please update ad unit code for beta.canonizer.com

**Right side panel  :**

<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6646446076038181"
     crossorigin="anonymous"></script>

<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-6646446076038181"
     data-ad-slot="7439786605"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>

**Left Side Panel**

<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6646446076038181"
     crossorigin="anonymous"></script>

<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-6646446076038181"
     data-ad-slot="7284670096"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>

**Comment by ks-rahul** [comment]
@gautamv16 as discussed on the skype call I'm looking for the updated link for both ads units.

**Comment by rupalichavan9860** [comment]
Verified by Ashutosh
