### ISSUE TITLE
Make Add/Edit news page private

### ISSUE THREAD

**Issue by shahab-ramzan** [the-canonizer/canonizer-3.0-frontend#612]
User authentication should be required for adding and editing the news

**Comment by shahab-ramzan** [comment]
PR Raised https://github.com/the-canonizer/canonizer-3.0-frontend/pull/627

**Comment by subhancd** [comment]
@shahab-ramzan  non-admin user can get the add news page by URL

![Image](https://user-images.githubusercontent.com/104552751/208033409-ae3a6ae7-a386-49b0-9385-9d1127c4f7d4.png)

**Comment by subhancd** [comment]
wroking fine on both staging and beta @rupalichavan9860
