### ISSUE TITLE
Thread title being cut off

### ISSUE THREAD

**Issue by ks-rahul** [the-canonizer/canonizer-3.0-frontend#617]
In the [page to post to a thread](https://beta.canonizer.com/forum/88-Theories-of-Consciousness/1-Agreement/threads/503), the title of the thread is being cut off.  There is room to show more of the title.

![Image](https://user-images.githubusercontent.com/6559312/206216079-e15f6994-6b6d-46ea-8411-b48f77d3d28e.png)

**Comment by rupalichavan9860** [comment]
@BrentAllsop As per the current implementation, the complete thread title is shown when the mouse is hovered over.
Please refer below screenshot : 

![image](https://user-images.githubusercontent.com/40416610/206658219-1a7fca06-2879-49f7-a52e-7b8772d36a15.png)

Is that okay?

**Comment by subhancd** [comment]
working fine on staging

**Comment by BrentAllsop** [comment]
> working fine on staging

By "staging" do you mean canonizer3.canonizer.com?

As it is really broken there:
![image](https://user-images.githubusercontent.com/6559312/207368739-a9b11220-0c9d-4b03-8fe6-6d7dc41acc60.png)
As you an see, not only can you not see the title, the mouse over doesn't show the correct title.

And it would be nice to have the mouse over show the entire title.
But it would also be nice to not clip the title name, where there is lots of space for more of the title.

**Comment by subhancd** [comment]
yes, by staging I mean canonizer3.canonizer.com
it is working as per the screenshot attached by Rupali. 

![Image](https://user-images.githubusercontent.com/104552751/207523581-07d3232b-7af3-450e-89bf-5b4f4e578d00.png)

**Comment by rupalichavan9860** [comment]
Verified on beta
