### ISSUE TITLE
remove support doesn't work for the following case

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/canonizer-3.0-frontend#640]
**Steps to reproduce**

1. create a topic
2. create 2 camps
3. support both camps
4. remove support from camp1
5. navigate to camp2 and click on remove support on topic detail page

**Actual Result**
remove support doesn't work
![Image](https://user-images.githubusercontent.com/104552751/207612272-00408198-1f2e-4a1e-9d83-ac602d791afd.png)

**Comment by subhancd** [comment]
working fine on staging. not working on beta @rupalichavan9860

**Comment by hassaanCD** [comment]
Tested and is working on production
