### ISSUE TITLE
preview image is missing in sharing on facebook

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/canonizer-3.0-frontend#643]
**Steps to Reproduce**

1. login with valid credentials
2. create a topic
3. click on share on facebook
4. navigate to facebook -> navigate to canonizer shared post
**Actual Result**

preview image is missing
![Image](https://user-images.githubusercontent.com/104552751/207793876-7e432151-00b2-4426-baba-fa1d44aa9bc9.png)

**Comment by ks-rahul** [comment]
@subhancd this was fixed. please check now.

**Comment by rupalichavan9860** [comment]
Working fine on live
