### ISSUE TITLE
Topic Detail Page : social media icons should be center aligned with camp forum button

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/canonizer-3.0-frontend#644]
**Steps to reproduce**

1. navigate to topic detail page

**Actual Result**
social media icons are top aligned with camp forum button

![Image](https://user-images.githubusercontent.com/104552751/207794461-f348447c-a316-46d8-b14c-f0dc19c3e800.png)

**Expected Result**
social media icons should be center aligned with the camp forum button

**Comment by subhancd** [comment]
working fine on staging

**Comment by hassaanCD** [comment]
Tested and is working on production
