### ISSUE TITLE
Fix Linting errors (iffort)

### ISSUE THREAD

**Issue by shahab-ramzan** [the-canonizer/canonizer-3.0-frontend#646]
Take latest pull from the development branch
replace these variables 
`"no-await-in-loop": "warning",
    "no-debugger": "warning",
    "no-console": "warning"`
with 
`"no-await-in-loop": "error",
    "no-debugger": "error",
    "no-console": "error"`

and run the build command there you will see a list of errors. Please fix them

**Comment by rupalichavan9860** [comment]
Verified by Ashutosh
