### ISSUE TITLE
Fix linting errors (Talentelgia)

### ISSUE THREAD

**Issue by shahab-ramzan** [the-canonizer/canonizer-3.0-frontend#647]
Take latest pull from the development branch
replace these variables
"no-await-in-loop": "warning", "no-debugger": "warning", "no-console": "warning",  "no-unused-vars": [
      "warning",
      {
        "varsIgnorePattern": "Window"
      }
    ]
with
"no-await-in-loop": "error", "no-debugger": "error", "no-console": "error",  "no-unused-vars": [
      "error",
      {
        "varsIgnorePattern": "Window"
      }
    ]

and run the build command there you will see a list of errors. Please fix them

**Comment by rupalichavan9860** [comment]
Verified By Ashutosh
