### ISSUE TITLE
Don't collapse branches if a camp has more than 50% support

### ISSUE THREAD

**Issue by shahab-ramzan** [the-canonizer/canonizer-3.0-frontend#664]
![Image](https://user-images.githubusercontent.com/6559312/207370680-074e80e0-8cac-4723-9119-fd6a75db8b6b.png)

By default, only the first level camps are shown.

![Image](https://user-images.githubusercontent.com/6559312/207370952-73c48a3c-d940-490f-902c-2b56ffa4841c.png)

For all of the hidden sub camps, like the Representational Qualia Theory shown here, which have more than 50% of the total support in the agreement, they should be expanded as shown here, by default.

![Image](https://user-images.githubusercontent.com/6559312/207373115-27b4e019-428f-428f-9d4c-a9a1eff2c5a3.png)

This should be true for all algorithms.  For example, when the Mind Expert algorithm is selected as shown in this image, even the "Property Dualism" camp has 50% of the agreement mind expert support.

And we want better controls of the tree, besides just saving the state in session.
We want to have a 2 buttons, one to open all sub camps, and one to close all sub camps.

**Comment by rupalichavan9860** [comment]
When you reload the page, this works perfectly, so I'm moving this ticket to "to do."
