### ISSUE TITLE
Make topic name, and bread crumbs larger

### ISSUE THREAD

**Issue by shahab-ramzan** [the-canonizer/canonizer-3.0-frontend#669]
![Image](https://user-images.githubusercontent.com/6559312/209482021-a5989923-92b2-4b8d-9746-f924a112f044.png)
As illustrated in the above image.  the actual topic name, and the breadcrumb camp names get lost in the noise of the page.
This information is more important than the word "Topic:" and "Camp:"  So the topic name, itself, and the breadcrumbs should be the ones that are bold, and they should be larger than the words "Topic:" and "Camp:".

And there should be a space both before and after the "/" separating each camp.  The "/" between the larger camp names can even be non bold, and smaller, the same as "Topic:" and "Camp:".

And the one that represent the camp in the breadcrumbs, should be green, as it is in the tree.  In the above camp page "Molecular Materialism" in the breadcrumbs should be green.

In my opinion, each of the camp names in the tree should also be blue, not just the agreement camp.

And when you mouse over them, there should be a more obvious change, like maybe get more bolded, darken the background, or something.

**Comment by rupalichavan9860** [comment]
@shahab-ramzan Can you please check below screenshot : 
![image](https://user-images.githubusercontent.com/40416610/210700772-7e5d29ef-bf5e-4b28-84d6-d4e3178471d7.png)

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by ks-rahul** [comment]
Verified on production.

**Comment by saniatg** [comment]
@rupalichavan9860 verified on production. Please confirm

**Comment by rupalichavan9860** [comment]
Verified
