### ISSUE TITLE
The current camp should never be collapsed in the tree on a topic page.

### ISSUE THREAD

**Issue by shahab-ramzan** [the-canonizer/canonizer-3.0-frontend#670]
![Image](https://user-images.githubusercontent.com/6559312/209482448-a9771e78-2518-4ea4-a9d9-86c79192025a.png)

Reproduce the problem with these steps:
1. I moved the "Qualia Emerge from Function" camp, under the new "Wave Theory of Consciousness" camp.
2. I immediately went to the "Wave Theory of Consciousness camp" before the change had gone live.
3. Then I changed to "include review" which caused the current "Qualia Emerge from Function" camp to be collapsed under the "Wave Theory of Consciousness camp".  The current "green" camp, should never be collapsed (and hidden) by default.  You need to be able to see where you are in the tree.

Also, the "Start new supporting camp here" link should never be collapsed.

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by rupalichavan9860** [comment]
Verified. @BrentAllsop Could you please check and close if everything is fine with you?

**Comment by BrentAllsop** [comment]
I tested this, and it looks great.
