### ISSUE TITLE
email template ui issues fix.

### ISSUE THREAD

**Issue by ks-rahul** [the-canonizer/canonizer-3.0-frontend#693]
![Image](https://user-images.githubusercontent.com/95217406/210203118-0ebbdaca-dbbc-4392-a51e-adc751405cee.png)

**Comment by rupalichavan9860** [comment]
@ks-rahul Reduce the indicated gap, please.
![image](https://user-images.githubusercontent.com/40416610/210770717-5bf514a6-6776-41a0-b8b6-9396a85aedf2.png)

**Comment by rupalichavan9860** [comment]
@ks-rahul Remove the background color, please
![image](https://user-images.githubusercontent.com/40416610/211551821-b288f8df-e98a-482c-a711-62abfbc6ad01.png)

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by saniatg** [comment]
@rupalichavan9860 working fine on production
![Screenshot 2023-02-21 at 4 02 44 PM](https://user-images.githubusercontent.com/91254708/220320916-0a64ef58-ba53-47eb-962c-fc03c7a9e395.png)

**Comment by rupalichavan9860** [comment]
Verified on live
