### ISSUE TITLE
Save state of what branches in the camp tree have been opened, and keep those open when you return to the same page.

### ISSUE THREAD

**Issue by shahab-ramzan** [the-canonizer/canonizer-3.0-frontend#696]
For example, if you expand a branch, then support a sub branch.
After you return to a camp page in the same topic, they are all closed, again.

And we need to add better controls, with at least an **expand all sub camps** (which should set the state in session, so every time you visit that topic, in your current session, it will remain fully expanded...)

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by hassaanCD** [comment]
fixed

**Comment by rupalichavan9860** [comment]
Verified
