### ISSUE TITLE
Trying to edit camp record, while not changing the name, says name is already taken.

### ISSUE THREAD

**Issue by shahab-ramzan** [the-canonizer/canonizer-3.0-frontend#697]
I tried to change the parent of a camp, but it wouldn't take the submit with the change, complaining the name was already in use.  (I didn't want to change the name, only the parent.)

**Comment by BrentAllsop** [comment]
Never mind.  I discovered that there are to camps in this topic with the name "Panexperientialism", which should have never been possible.  So, I have change the name of one of them to "Panexperientialism 2".  Problem solved.
