### ISSUE TITLE
Changes don't take effect, if you select edit after the 1 hour commit timer starts.

### ISSUE THREAD

**Issue by shahab-ramzan** [the-canonizer/canonizer-3.0-frontend#698]
If you edit a statement, then select commit it starts the 1 hour countdown timer, giving you a chance to edit the change.  But any changes made during this time do not take affect.

Also the count down option needs a cancel submit button which will just remove the record.

**Comment by hassaanCD** [comment]
not fixed

**Comment by saniatg** [comment]
Any changes made before commit is working fine on staging
And this  "Also the count down option needs a cancel submit button which will just remove the record." changes is being implemented in ticket 
https://github.com/the-canonizer/canonizer-3.0-api/issues/576

**Comment by saniatg** [comment]
Working fine on production 
And this "Also the count down option needs a cancel submit button which will just remove the record." changes is being implemented in ticket
https://github.com/the-canonizer/canonizer-3.0-api/issues/576
