### ISSUE TITLE
Integrate custom skeleton (home page / browse page / topic details and on all history pages)

### ISSUE THREAD

**Issue by shahab-ramzan** [the-canonizer/canonizer-3.0-frontend#701]

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by ks-rahul** [comment]
@rupalichavan9860 on the production topic details page all cards have shown "no found" text for some time and then the skeleton is visible.

**Comment by rupalichavan9860** [comment]
@shahab-ramzan Will you kindly check?

**Comment by rupalichavan9860** [comment]
Working fine on both staging and live
