### ISSUE TITLE
Ad is not responsive

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#711]
Resolution: 425*635

Note: See attached image

![Image](https://user-images.githubusercontent.com/120023458/210553324-c33f3d7a-2d1d-4acc-8111-a2aa6f1ce8a0.png)

**Comment by ks-rahul** [comment]
@hassaanCD please check now.

**Comment by rupalichavan9860** [comment]
Ads are removed , so this is working fine now

**Comment by hassaanCD** [comment]
Tested and is working on production
