### ISSUE TITLE
Change search box config

### ISSUE THREAD

**Issue by mark-shamy** [the-canonizer/canonizer-3.0-frontend#713]
Google based search box currently using
`site:canonizer3.canonizer.com`

Change to 
`site:canonizer.com`

**Comment by rupalichavan9860** [comment]
Not working

**Comment by vikasranatalentelgia** [comment]
@gautamv16 the value of env variable "NEXT_PUBLIC_SITE_NAME" should be "canonizer.com" to make it work

**Comment by vikasranatalentelgia** [comment]
@rupalichavan9860 working
