### ISSUE TITLE
Skeleton should be there instead of "No data" icon and loader should not be there

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#733]
Note: See attached image

![Image](https://user-images.githubusercontent.com/120023458/212848459-53abc800-9b53-40e1-9d4b-3a309375e71d.png)

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by saniatg** [comment]
@rupalichavan9860 Tested and is working fine on production

**Comment by rupalichavan9860** [comment]
Verified on live
