### ISSUE TITLE
Skeleton should be there instead of loader in "Recent Activity" panel

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#735]
Note:  see attached image

![Image](https://user-images.githubusercontent.com/120023458/212852027-133d272b-b916-4168-980b-b85a23460c0a.png)

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by saniatg** [comment]
@rupalichavan9860 tested and is working fine on production.

**Comment by rupalichavan9860** [comment]
Verified on live
