### ISSUE TITLE
Integrate custom skeleton(instead of "No data") on Camp Forum (List of All Camp Threads)

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer-3.0-frontend#745]
![image](https://user-images.githubusercontent.com/40416610/213650145-28825ded-f381-48f6-ac02-4a9377a42fcc.png)

![image](https://user-images.githubusercontent.com/40416610/213650221-068efcdd-ddca-4244-ab6a-0d22f0231f9b.png)

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by hassaanCD** [comment]
Tested and is working on production
