### ISSUE TITLE
Skeleton layout issue on bread crumb

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer-3.0-frontend#747]
Please refer attached screenshot : 

![image](https://user-images.githubusercontent.com/40416610/213694201-90913080-c927-44b0-a80a-1985028681c8.png)

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by saniatg** [comment]
@rupalichavan9860 working fine on production

**Comment by rupalichavan9860** [comment]
Verified
