### ISSUE TITLE
Skeleton layout issue on Supported Camps and Subscription 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer-3.0-frontend#748]
Please refer attached screenshot : 
Supported Camps : 
![image](https://user-images.githubusercontent.com/40416610/213695052-91e7e06c-fb8d-41a3-8ed0-cd58cd343ce2.png)

Subscription : 
Displaying skeleton for one record only 
![image](https://user-images.githubusercontent.com/40416610/213695319-da6d9263-ab6d-4e2e-a3e0-fd18b1c22ec7.png)

![image](https://user-images.githubusercontent.com/40416610/213695383-be292593-7fc9-4eb0-8511-def788466cf2.png)

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by hassaanCD** [comment]
Tested and is working on production
