### ISSUE TITLE
direct supporters of sub camps can't object

### ISSUE THREAD

**Issue by shahab-ramzan** [the-canonizer/canonizer-3.0-frontend#762]
I was a direct supporter of a sub camp to [this agreement camp](https://canonizer.com/statement/history/570/1), when Jim proposed an edit to the statement.  The 3.0 system wouldn't let me object.  But I was able to object using the 2.0 system.

**Comment by rupalichavan9860** [comment]
@shahab-ramzan This is not yet resolved. As discussed, please see the 2.0 ticket below for a more detailed understanding.

https://github.com/the-canonizer/canonizer.2.0/issues/517

**Comment by rupalichavan9860** [comment]
@shahab-ramzan The Object button is activated, but it displays "Why can't I object?" instead of the objection page

**Comment by DevAlchemyCD** [comment]
@rupalichavan9860  this ticket done with #869

**Comment by saniatg** [comment]
@rupalichavan9860 this is working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by saniatg** [comment]
@rupalichavan9860 Tested and is working fine on production
