### ISSUE TITLE
Skeleton issue in delegated supported camp tab

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#765]
Steps to reproduce:
1- Login to the canonizer. 
2- Go into the account setting -> Supported camps.
3- Go in the second tab of delegated supported camps. 
4- Remove all delegated supports. 
5- Now on reload of page , skeleton still loading continuously.

![Image](https://user-images.githubusercontent.com/120023458/215082103-18457bfc-bd3e-4a7b-8cb2-801305234663.png)

**Comment by rupalichavan9860** [comment]
This issue persists in both direct and delegated support camps.

**Comment by vikasranatalentelgia** [comment]
@rupalichavan9860 it's working

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on live
