### ISSUE TITLE
We need to add a URL ? argument to the home page and browse page, so you can specify a namespace setting.

### ISSUE THREAD

**Issue by ks-rahul** [the-canonizer/canonizer-3.0-frontend#772]
For example:
http://canonizer.com/?namespace=/government/sandy_city/
This URL would go to the home page, and also set the namespace to /government/sandy_city/

https://canonizer.com/browse?namespace=/government/sandy_city/

**Comment by mark-shamy** [comment]
This issue is now being considered urgent, Brent needs it complete before presenting Canonizer to a city official.

**Comment by rupalichavan9860** [comment]
@BrentAllsop Could you please check and confirm that this URL is appropriate for you?

https://canonizer3.canonizer.com/?namespace=%2FGeneral%2F

![image](https://user-images.githubusercontent.com/40416610/217469628-dcdaddb8-18c1-4ffa-b97a-83cc6a86e570.png)

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on live
