### ISSUE TITLE
Skeleton is not aligned within the box on "Manage Support" page

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#793]
Note: As shown in attached screenshot

![Image](https://user-images.githubusercontent.com/120023458/217733946-999a67b4-e4c8-498a-8d43-c3d0efa77d97.png)

**Comment by hassaanCD** [comment]
while adding support

**Comment by rupalichavan9860** [comment]
Working fine on live
