### ISSUE TITLE
Home page and browse page crashed on staging

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#798]
Home and Browse page is crashed when "Include Review" filter is applied.

**Steps to reproduce**

- Create a Topic from User A.
- Add a statement from User B and commit.
- Go to Browse page from User A.
- Search for this topic.
- Apply "Include Review" Filter.
- Just refresh the page.

**Actual Result**
Page crashed

![Image](https://user-images.githubusercontent.com/120023458/218090152-8464ae54-cc5e-4ccd-adf5-7df8c663c77b.png)

**Comment by hassaanCD** [comment]
fixed

![s1](https://user-images.githubusercontent.com/120023458/221867493-cd050bff-0022-46a3-8bbd-90d4e9282a74.png)

**Comment by rupalichavan9860** [comment]
Verified on live
