### ISSUE TITLE
Delegated Support count is not working correctly on removing  on staging and on live

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer-3.0-frontend#800]
Steps:

1. User A created a topic and a camp1
2. Supported camp1
3. User B delegated support to User A in camp 1
4. Now User A click on remove support button 

Actual result: instead of removing score , the users vote count becomes double
Expected Result: Score must be removed

![Screenshot 2023-02-13 at 1 11 44 PM](https://user-images.githubusercontent.com/91254708/218399559-88fdd469-7910-41e1-8af8-57509739c30e.png)
![Screenshot 2023-02-13 at 1 12 30 PM](https://user-images.githubusercontent.com/91254708/218399623-1173f189-601f-41fc-807c-31d21154284f.png)

**Comment by vikasranatalentelgia** [comment]
@karun0607gautam , I have checked and the API https://service.canonizer.com/api/v1/tree/get is returning the removed nickname in the support tree array after remove. But after refreshing, it gives the correct response. Please check
![image](https://user-images.githubusercontent.com/98095849/218464124-5b17de0b-3534-49a1-9a95-13c7e90b0117.png)
![image](https://user-images.githubusercontent.com/98095849/218464246-fcaad05d-e4db-4ba4-831c-bcf04c5481de.png)

**Comment by saniatg** [comment]
Tested and is working fine on staging.

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
Tested and is working fine on production @rupalichavan9860
