### ISSUE TITLE
Object button is not showing in the following case

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer-3.0-frontend#801]
Steps:

1. User A created a topic and supported it
2. User B delegated support to user A
3. User A created a camp and then supported the camp and support is removed from agreement
4. User B submitted statement for agreement and is in review

Login with user A, the object button is seen disabled

**Comment by saniatg** [comment]
@vikasranatalentelgia issue not fixed. As a direct supporter not able to object.
![Screenshot 2023-02-28 at 1 08 37 PM](https://user-images.githubusercontent.com/91254708/221786138-bd795606-1c8c-415b-842d-7862882082fa.png)

**Comment by rupalichavan9860** [comment]
Related ticket : https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/issues/193

**Comment by saniatg** [comment]
@vikasranatalentelgia not fixed

I'm getting error "You are not authorized to object to this statement because you do not support this camp."
![Screenshot 2023-03-07 at 5 18 09 PM](https://user-images.githubusercontent.com/91254708/223413743-0ef57df8-ff34-4dff-9802-615b7fb980a3.png)

**Comment by nalwa** [comment]
@saniatg  and @rupalichavan9860  this is working fine. can you guys re-test it again and verify ?

**Comment by saniatg** [comment]
Yes it is working fine now.
