### ISSUE TITLE
Upload a new video

### ISSUE THREAD

**Issue by ashish76** [the-canonizer/canonizer-3.0-frontend#809]

**Comment by ashish76** [comment]
Hi @BrentAllsop,

As you mentioned in the weekly call, Could you please provide the video which is to be uploaded to the application?

**Comment by hassaanCD** [comment]
Not fixed on staging but working fine on production


![Image](https://user-images.githubusercontent.com/120023458/221786347-b781b561-5441-4596-8bc9-8953460dd911.png)




![Image](https://user-images.githubusercontent.com/120023458/221786694-6f512558-290a-4f45-88e5-15e491680c93.png)

**Comment by array-junkie** [comment]
It is working fine on Staging & Live.

**Comment by hassaanCD** [comment]
fixed and working fine on both staging and live



![Image](https://user-images.githubusercontent.com/120023458/222652525-45e18ee4-dafe-4a6f-91fb-cc413db47510.png)




![Image](https://user-images.githubusercontent.com/120023458/222652912-651eb1a6-f065-4aa9-9082-aa02b807da69.png)

**Comment by rupalichavan9860** [comment]
Verified on staging and live
