### ISSUE TITLE
Remove support is not working correctly

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer-3.0-frontend#810]
Steps:

1. Create a topic, support is for agreement camp
2. Now click on "remove your support"
3. Support is removed
4. Add support again to agreement
5. Now click on "remove your support" again

Actual result: support is not removed instead 0.5 vote is seen which is incorrect
Expected result: support must be removed
![Screenshot 2023-02-16 at 11 34 57 AM](https://user-images.githubusercontent.com/91254708/219282660-68372abf-ed5d-46f1-bab2-747bad8de929.png)

**Comment by saniatg** [comment]
working fine on reload

**Comment by vikasranatalentelgia** [comment]
@karun0607gautam its the same issue as mentioned in ticket #800

**Comment by saniatg** [comment]
Tested and is working fine on staging

**Comment by rupalichavan9860** [comment]
Verified

**Comment by ks-rahul** [comment]
@rupalichavan9860 @saniatg  

working fine on production, 

after removing the support it's removed and topic score is 0.




![Image](https://user-images.githubusercontent.com/95217406/220318512-16b130a7-9490-4634-bb02-a20b59a0f043.png)

**Comment by saniatg** [comment]
Working fine on production
