### ISSUE TITLE
Implement Topic detail page "Score bar" length conditionally

### ISSUE THREAD

**Issue by sajid315** [the-canonizer/canonizer-3.0-frontend#814]
On Topic detail page, yellow score bar for the topic should be increased in length only when the main parent score will be more than 5.00 .

![Image](https://user-images.githubusercontent.com/120023458/218071149-eda2bef2-6143-4aef-b2db-38347da2d97b.png)

**Comment by hassaanCD** [comment]
fixed

![t0](https://user-images.githubusercontent.com/120023458/222141335-aae98911-1ef5-4826-a53d-2c867c7b5cac.png)


![t1](https://user-images.githubusercontent.com/120023458/222141414-461b2297-2c63-4484-be6e-e28763d567ac.png)

**Comment by rupalichavan9860** [comment]
@shahab-ramzan Can't see score bar for new topics : 
![image](https://user-images.githubusercontent.com/40416610/222462406-9dc813de-7bd5-4a0b-8dc0-577ce5984c3c.png)

**Comment by shahab-ramzan** [comment]
@rupalichavan9860 According to our conditions the score bar will grow only if 

- the scores of agreement camp is  greater than 5
- there is at least two camps in the topic (including agreement camp)

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by rupalichavan9860** [comment]
Verified on live
