### ISSUE TITLE
Change the position of disclaimer text

### ISSUE THREAD

**Issue by ashish76** [the-canonizer/canonizer-3.0-frontend#815]
Change the position of the disclaimer text **_(This is a free [open source ](https://github.com/the-canonizer/canonizer-3.0-frontend)prototype being developed by volunteers. Please be patient with what we have so far and/or be willing to help.)_** from header to footer. 

The text will be placed below the Canonizer logo in the footer.

**Comment by ashish76** [comment]
@mark-shamy & @BrentAllsop Is there any change in the existing text? If yes, please provide the text.

**Comment by ashish76** [comment]
The new text suggested by Jim is 
Canonizer is an open-source project designed to build consensus and bring people together. Your collaboration can make all the difference. Join us!

**Comment by saniatg** [comment]
@rupalichavan9860 position of the text  and text content is fine. I have a doubt, when click on " open source" link in the text  it redirects to https://github.com/the-canonizer/canonizer-3.0-frontend. It is okay. Please confirm

**Comment by rupalichavan9860** [comment]
@saniatg fine

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by rupalichavan9860** [comment]
Verified on live
