### ISSUE TITLE
When delegating support duplicate camp names are showing under supported camps

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer-3.0-frontend#819]
Steps:

1. User  A creates a topic and support is automatically added for agreement camp
2. User A creates a camp:'camp1'
3. User B adds support to 'camp1'
4. User A clicks on delegate support

duplicate camp names are showing under supported camps
![Screenshot 2023-02-20 at 3 02 14 PM](https://user-images.githubusercontent.com/91254708/220071524-381c117c-b45e-4c4b-87f5-2625ff5d1bb3.png)

**Comment by saniatg** [comment]
@rupalichavan9860 working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on live
