### ISSUE TITLE
Support count is not visible. UI is distorted on live

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer-3.0-frontend#826]
![Screenshot 2023-02-21 at 3 17 08 PM](https://user-images.githubusercontent.com/91254708/220310227-68143991-0829-40fb-a494-de35f6814ebf.png)

**Comment by saniatg** [comment]
@rupalichavan9860 this ticket can be tested on production , not on staging as the issue is on live not on staging and it the issue is still there on live

**Comment by rupalichavan9860** [comment]
Yes

**Comment by rupalichavan9860** [comment]
Verified on live
