### ISSUE TITLE
Issue in the skeleton design on staging and on live , the submit button is small

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer-3.0-frontend#827]
![image_2023_02_21T09_54_05_109Z](https://user-images.githubusercontent.com/91254708/220313708-bba2b8d4-d6f2-40c5-82f5-6a2dd208cf36.png)
When creating topic

**Comment by saniatg** [comment]
@rupalichavan9860 tested and is working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on live
