### ISSUE TITLE
Duplicate API call on "ManageSupport" Page.

### ISSUE THREAD

**Issue by array-junkie** [the-canonizer/canonizer-3.0-frontend#830]
**Steps to reproduce**

1. Create a topic from User A.
2. Support "Agreement" Camp from User B.
3. Delegate support from User A.

In the networks tab, api are called multiple times.

![Image](https://user-images.githubusercontent.com/100785013/220549888-53329d7c-2ad9-4e13-bc7e-45530861e1d9.png)

**Comment by hassaanCD** [comment]
Not fixed



![Image](https://user-images.githubusercontent.com/120023458/221834836-2db10693-c9c9-4079-8056-dd4f02324878.png)

**Comment by hassaanCD** [comment]
Not fixed



![Image](https://user-images.githubusercontent.com/120023458/223434068-0e0ed17f-bac2-47ab-8cc9-aa256fa06cb7.png)

**Comment by vikasranatalentelgia** [comment]
@hassaanCD it seems the code is not deployed on staging. there is only one call to API in local.
![image_2023_03_09T07_55_30_757Z](https://user-images.githubusercontent.com/98095849/223966681-be804d51-d5c5-4cae-8a70-cbefba67dccc.png)

**Comment by hassaanCD** [comment]
@vikasranatalentelgia okay. Let me know when the code will be deployed on staging. I will verify again.

**Comment by vikasranatalentelgia** [comment]
@hassaanCD , it is working as expected.
