### ISSUE TITLE
Add SEO Tags to Topic Animation Page

### ISSUE THREAD

**Issue by shahab-ramzan** [the-canonizer/canonizer-3.0-frontend#845]

**Comment by shahab-ramzan** [comment]
@sunnyjindal  Can you please provide SEO content for Topic Animation's page.
https://docs.google.com/spreadsheets/d/1gjQ9bi2xxky30LzpKgAAyh1BSTjCwNpDHi87oAb49HM/edit#gid=0

**Comment by array-junkie** [comment]
PR has been raised: [#601](https://github.com/the-canonizer/canonizer-3.0-api/pull/601)

**Comment by rupalichavan9860** [comment]
Verified by Ashutosh
