### ISSUE TITLE
Move 100% Score Control

### ISSUE THREAD

**Issue by mark-shamy** [the-canonizer/canonizer-3.0-frontend#847]
Move "fullScore_score_checkbox__RZDAZ" from out of the collapsible section to after Filter > control and delete collapsible section. 

![Image](https://user-images.githubusercontent.com/8573895/222984505-6ee37136-d80c-44a7-998b-b0dae9648181.png)

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by rupalichavan9860** [comment]
Verified on live
