### ISSUE TITLE
Homepage Hot Topic

### ISSUE THREAD

**Issue by mark-shamy** [the-canonizer/canonizer-3.0-frontend#849]
Create "Hot Topic" component for homepage that displays a camp statement, it's parent Topic and Canon, and edit date configurable from admin backend.

**Comment by mark-shamy** [comment]
![Image](https://user-images.githubusercontent.com/8573895/222984836-d6b48083-ef97-4928-831b-59b6fd79330a.png)

**Comment by ashish76** [comment]
Based on the demo held on 24-Aug-2023, a few suggestions came up with the team. Following are the points that need to be incorporated into this feature

1. There should be a provision to link a camp to the hot topic.
2. We have to restrict the file size and the resolution of the image we are uploading. A message should be visible in the interface to let the user know about it
3. There should be a provision to preview the hot topics being created. 
4. On Submit the form the topic will be stored as in-review state. 
5. The user has to publish the topic manually. When the user clicks on the publish button, a preview will be shown to the user, and on the confirmation, the topic will be marked as published and the previous will be achieved. Users can publish it from inside the Form and the list.
6. There should be a provision to re-publish the archived topics from the list
7. In the list, 3 different sections will be displayed 
- Live (Green)
- In Review (Yellow)
- Archived (Blue)

@BrentAllsop, @mark-shamy @cd-ali-ehsan, @sunnyjindal, @rohit-talentelgia & @gautamv16 Please look at the above and let me know if I missed any points. Thank you

**Comment by cd-ali-ehsan** [comment]
@rupalichavan9860, @ashish76 is waiting for the testcases for this ticket.

**Comment by rupalichavan9860** [comment]
We have implemented the hot topic and are tracking any issues separately, so we are closing this ticket.

**Comment by rupalichavan9860** [comment]
Hot topic is implemented
