### ISSUE TITLE
Remove Camp Statement Preview Button

### ISSUE THREAD

**Issue by mark-shamy** [the-canonizer/canonizer-3.0-frontend#856]
Now that the camp statement editor is WYSWYG, there is no longer a need to preview before submitting. This preview functionality is broken anyways.

**Comment by sajid315** [comment]
@mark-shamy so we will remove preview from all form pages like topic, camp and statement. Right ? 
@wahaj-hafeez removing it now.

**Comment by sajid315** [comment]
https://github.com/the-canonizer/canonizer-3.0-frontend/pull/881/files

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by saniatg** [comment]
Not fixed on Production @sajid315 for statement , topic and camp 
![Screenshot 2023-03-24 at 1 37 17 PM](https://user-images.githubusercontent.com/91254708/227461863-38a220b3-0075-40a6-b09a-db1b118fe9a3.png)
![Screenshot 2023-03-24 at 1 38 30 PM](https://user-images.githubusercontent.com/91254708/227461881-e6c40856-6a07-489d-a324-4db66b2b5c72.png)

![Screenshot 2023-03-24 at 1 39 08 PM](https://user-images.githubusercontent.com/91254708/227462050-844fbbd0-fab1-4f03-bfa0-57a224637e2d.png)

**Comment by saniatg** [comment]
Fixed now on production after Ashutosh rebuilding the application
