### ISSUE TITLE
Never hide the "Start new supporting camp here" option, unless selected.

### ISSUE THREAD

**Issue by shahab-ramzan** [the-canonizer/canonizer-3.0-frontend#858]
Normally, when you first go to a camp statement, from a URL, the "Start new supporting camp here" option is not hidden.  However, if you go to another camp for the first time, the option will then be hidden on the new camp, when you arrive.
It should never be hidden, unless the person explicitly hides it.

**Comment by sajid315** [comment]
PR raised and merged in development.
https://github.com/the-canonizer/canonizer-3.0-frontend/pull/870

**Comment by saniatg** [comment]
Working fine on staging.

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by hassaanCD** [comment]
Working fine on production
