### ISSUE TITLE
Add an ability to "archive" a camp.

### ISSUE THREAD

**Issue by mark-shamy** [the-canonizer/canonizer-3.0-frontend#862]
Add an "archive" switch for camps.
Also add a check box in the "canonizer algorithm" section to "Show archived camps" under "100% of canonized score on all supported camps". Default behavior is unchecked, archived camps are not shown and scores for archived camps are never counted.

https://canonizer.com/topic/8-Suggestion-Box/25-Camp-and-Topic-Archiving

When visiting an archived camp, a banner should be displayed indicating it as such. For SEO, the tag `<meta name="robots" content="noindex">` should be added the HTML head of the page.

**Comment by mark-shamy** [comment]
![Image](https://user-images.githubusercontent.com/8573895/224456207-20645b8c-6476-4afa-a997-c6730924a3fe.png)

Add archive check box to manage camp record

**Comment by mark-shamy** [comment]
Archived camps are never shown on user's profile

**Comment by nalwa** [comment]
@rupalichavan9860  please provide the acceptance criteria  ans test cases for this functionality.

**Comment by rupalichavan9860** [comment]
@mark-shamy I have below queries on this. Could you please check and update ?

User A is supporting below camps 

Camps      Support Order
Camp 1            1
Camp 2            2
Camp 3            3
Camp 4            4
Camp 5            5

If User A submitted a camp change : "Camp 3" --Select "Camp Archived", it will go live immediately 

Question 1 : Support will stay the same as it is in the database? Or will it also result in the termination of DB support?


If database support will be available
Case 1 : Camp is Archived and Default behavior is unchecked-- archived camps will not show and scores for archived camps will never counted.
What will be the support order then be?
Camps      Support Order
Camp 1            1
Camp 2            2
Camp 4            3
Camp 5            4

Is this the order for support ?


Case 2 : Camp is Archived and Default behavior is checked-- archived camps will show 
Is score will be calculated for archived camps?
What will be the support order then be?
Camps      Support Order
Camp 1            1
Camp 2            2
Camp 3            3
Camp 4            4
Camp 5            5

Is this the order for support ?

Case 3 : "Camp 3 " is archived and unarchived again, What will be the support order then be?

**Comment by mark-shamy** [comment]
![Image](https://user-images.githubusercontent.com/8573895/227318443-4a29b09f-5666-4b17-b219-53d2498fef0d.png)

**Comment by rupalichavan9860** [comment]
As functionality has been implemented and we are logging issues separately, we are closing this.

**Comment by rupalichavan9860** [comment]
Verified on live
