### ISSUE TITLE
Id's are not set in several buttons.

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/canonizer-3.0-frontend#878]
1.Add Camp Statement.
2.Manage/Edit Topic.
3.Manage/Edit Camp.
4.Directly Join Support.
5.For Elements inside "Add Camp Statement Page".
6.For Elements inside "Topic Update Page".
7.For Elements inside "Camp Update Page".

**Comment by akashgit77** [comment]
![Image](https://user-images.githubusercontent.com/105647543/225831709-0e7a28d6-839d-400e-ae99-bfb63e787d14.png)

We need Id for "Add Camp Statement" button.

**Comment by rupalichavan9860** [comment]
Working fine on live
