### ISSUE TITLE
On the supported camp page, page disappear after page refresh

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#916]
Steps to reproduce :

Create New Topic (User is supporter of Agreement camp)
Click on "Event Line" button
Click on "Back"
Click on "Manage Support" button
Refresh the page
Observe page
Actual Result : Page disappear after page refresh as shown in attached screenshot

![Image](https://user-images.githubusercontent.com/120023458/229076186-d13f83a1-a5b3-4da9-b429-ee53fc3ed00b.png)

**Comment by vikasranatalentelgia** [comment]
it is already fixed in ticket #250
https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/issues/250

**Comment by hassaanCD** [comment]
Fixed



![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/d73a528b-fb47-4ea1-8408-37a912216ca3)

**Comment by SandeepTalentelgia** [comment]
Closed, verified over the live server.
