### ISSUE TITLE
UI issues in "Event Line" page

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#918]
As shown in attached screenshot below: 

![Image](https://user-images.githubusercontent.com/120023458/229108757-4b543e77-1b31-48c9-91cd-6a05acecc7c1.png)

**Comment by hassaanCD** [comment]
Fixed



![Image](https://user-images.githubusercontent.com/120023458/229698496-a1d49482-b346-404d-84ca-44ab41c5c9f7.png)

**Comment by rupalichavan9860** [comment]
Working fine now
