### ISSUE TITLE
Submit statement update issue

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#922]
Steps to reproduce

- Login with user A and create a new topic
- Login with user B and add statement to that topic
- Observe Statement

![Image](https://user-images.githubusercontent.com/120023458/229093742-042357c8-f7e3-4876-b6c9-bbd7caa13be4.png)

- Click on "edit change" button without commit change
- Edit statement in editor and click on submit button
- Observe Statement 

![Image](https://user-images.githubusercontent.com/120023458/229094747-d77e935b-eba3-4b0d-b934-3b9ef921790f.png)

-Now click on "submit statement update" button
-Observe statement in editor

![Image](https://user-images.githubusercontent.com/120023458/229095339-cd3756df-622b-4bbf-babb-5798add67f80.png)

-Actual Result: It is showing "before edit" statement

**Comment by sajid315** [comment]
@shahab-ramzan From back-end we verified the responses so we just need to utilize "parsed_value" and "value" key in response to sort out this problem.

**Comment by hassaanCD** [comment]
Fixed

**Comment by hassaanCD** [comment]
Working fine on production



![Image](https://user-images.githubusercontent.com/120023458/231381363-8e9fcca4-204d-4977-86b6-418bb9326f49.png)
