### ISSUE TITLE
"Submit Update" button is not working in "Camp Update" page

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#925]
Steps to reproduce:

-Login with User A and create topic and create camp "camp01"
-Create sub camp "subCamp01"
-Login with User B and change camp name to " camp01 New" from "camp01"
-Observe "Submit Update" button

Actual result: "Submit Update" button is not enabled

![Image](https://user-images.githubusercontent.com/120023458/229713643-d3df4a81-3596-48d1-b594-0bec0550bb4b.png)

**Comment by hassaanCD** [comment]
"Submit Update" button still disable when add "Keywords", "Camp About URL" and "Camp About Nickname". As shown in attached screenshot below:



![Image](https://user-images.githubusercontent.com/120023458/230012629-f19dc389-5a40-4916-8d3a-49c577abd87d.png)

**Comment by SandeepTalentelgia** [comment]
Not fixed

![Image](https://user-images.githubusercontent.com/129028750/236387842-005da603-4c21-4804-8266-16aa24f91872.png)

**Comment by shahab-ramzan** [comment]
@SandeepTalentelgia Code is not merged yet for this issue. 
https://github.com/the-canonizer/canonizer-3.0-frontend/pull/991

**Comment by rupalichavan9860** [comment]
Not fixed

**Comment by hassaanCD** [comment]
Working fine on staging for "Camp name", "Keywords", "Camp About URL" and "Camp About Nickname".



![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/89d11fa7-25e2-4f78-8b7f-8c584c39b28c)

**Comment by hassaanCD** [comment]
Working fine on production



![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/ab972a84-0b33-4b1a-80b1-93f3cb45b2ae)




![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/96edb42c-f2ef-490d-b287-183fe4b1240a)
