### ISSUE TITLE
Text "[object Object]" is already shown in "Edit Summary text box" when open "Add Camp Statement" page

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#928]
Steps to reproduce

-Login with user A and create a new topic
-Login with user B and add statement to that topic
-Observe "Edit Summary text box"

![Image](https://user-images.githubusercontent.com/120023458/229739080-a4c1c232-839e-4109-bd75-bedd5665e08e.png)

**Comment by rupalichavan9860** [comment]
Same for Topic Update page

![image](https://user-images.githubusercontent.com/40416610/229869808-be978d8c-a105-4320-938d-d6b836e3552e.png)

**Comment by hassaanCD** [comment]
![Image](https://user-images.githubusercontent.com/120023458/230011504-912546f4-5d10-4f70-82c1-ce5d6adc230b.png)

**Comment by hassaanCD** [comment]
Not fixed



![Image](https://user-images.githubusercontent.com/120023458/231063767-565dce95-c13c-422c-bcf3-4c41762b0aa2.png)




![Image](https://user-images.githubusercontent.com/120023458/231063809-f8fe83f7-60a4-4336-b7b7-0b4252ef67f3.png)




![Image](https://user-images.githubusercontent.com/120023458/231063830-89c91818-d950-43e9-94f2-16e382b13cfa.png)

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on live
