### ISSUE TITLE
"Play button" is not working in "Event line" page

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#932]
As shown in attached screenshot below:

![Image](https://user-images.githubusercontent.com/120023458/229781765-d92024a2-dbbf-477c-bcd9-603bf27e9a4c.png)

**Comment by hassaanCD** [comment]
Fixed



![Image](https://user-images.githubusercontent.com/120023458/234888252-0e602534-9d97-4a9e-b9af-63fdedd439e3.png)

**Comment by sandeeptlgt** [comment]
Closed, verified on live.
