### ISSUE TITLE
"Submit Objection" is not working in "Statement object", "Topic object" and "Camp object" pages

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#935]
Steps to reproduce:

-Login with User A and create topic and create camp "camp01"
-Support the camp 'camp01' with user A
-Login with User B and change camp name / topic name / Add statement 
-Again login with user A, go to camp/statement/topic history page
-Object camp/topic/statement change 
-Now observe Submit Objection button. It is not working

Actual result: "Submit Objection" button is not enabled

![Image](https://user-images.githubusercontent.com/120023458/230022302-5a1eada4-ba4d-4d9c-9eec-535374dbb1fd.png)

**Comment by hassaanCD** [comment]
Fixed



![Image](https://user-images.githubusercontent.com/120023458/233266139-fca6c18d-1281-46fe-95d3-bdf518d58a00.png)

**Comment by rupalichavan9860** [comment]
Verified on live
