### ISSUE TITLE
Statement text format is not correct

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#937]
As shown in attached screenshot below:

![Image](https://user-images.githubusercontent.com/120023458/230044814-e196988b-6259-4a16-90aa-aff244e67073.png)

**Comment by hassaanCD** [comment]
Seems like above special characters are not coming now, but after PR raise we can check more cases thoroughly.

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/7c8e0954-5cd3-4c4d-9d79-dbe30486bbaa)

**Comment by shahab-ramzan** [comment]
@hassaanCD this issue is fixed. Can you please verify?

**Comment by hassaanCD** [comment]
@shahab-ramzan Yes. It is fixed.



![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/a24d343a-dd44-4c7a-b06b-38eef7cc9b22)

**Comment by rupalichavan9860** [comment]
Working fine on live
