### ISSUE TITLE
Supporter Count Bars are not expanding

### ISSUE THREAD

**Issue by array-junkie** [the-canonizer/canonizer-3.0-frontend#939]
Please refer to the screenshot: 

![Image](https://user-images.githubusercontent.com/100785013/230293046-b01054c4-59ad-4554-a06a-72d18d9058c1.png)

**Comment by hassaanCD** [comment]
Not fixed



![Image](https://user-images.githubusercontent.com/120023458/231064798-6b1249d5-92f3-4042-a2a0-4597fdfb2395.png)

**Comment by rupalichavan9860** [comment]
Working fine on both staging and live
