### ISSUE TITLE
Rename "Namespace" to "Canon"

### ISSUE THREAD

**Issue by ks-rahul** [the-canonizer/canonizer-3.0-frontend#950]

**Comment by ks-rahul** [comment]
@mark-shamy please elaborate more about this ticket where need to update the text UI or URL.

**Comment by ashish76** [comment]
Based on the discussion we had on the weekly call, it is decided that change the Namespace word across the website.
For backward compatibility: we will rewrite the URL on the client side so that it will be the same for all cases.

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on live
