### ISSUE TITLE
"Camp Name" is not showing in "Support Tree"

### ISSUE THREAD

**Issue by shahab-ramzan** [the-canonizer/canonizer-3.0-frontend#951]
Steps to reproduce :

-Create topic
-Create camp "Camp1"
-Create sub camp of "Camp1" - "SubCamp1" and support "SubCamp1"
-Login with User B and change camp name from "Camp1" to "Camp1 updated"
-Commit changes
-Login with User A again
-Apply filter "Include Review"
-Try to support "Camp1"
-Observe "Support Tree" jus before it navigate to "Supported Camp" page

![Image](https://user-images.githubusercontent.com/120023458/231356505-6792b31e-1164-4843-af5e-1288a16cf038.png)

**Comment by hassaanCD** [comment]
Fixed



![Image](https://user-images.githubusercontent.com/120023458/233261564-6830c5f6-38c3-40c1-a549-650a2deefba4.png)

**Comment by rupalichavan9860** [comment]
Verified on live
