### ISSUE TITLE
On every camp change in a topic tree UI gets blocked

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#956]
Please refer to the attached screenshot

![Image](https://user-images.githubusercontent.com/120023458/231667439-fa90d596-b5df-4e78-b133-66d302611f86.png)

**Comment by hassaanCD** [comment]
Fixed



![Image](https://user-images.githubusercontent.com/120023458/233398479-939a5027-2caf-42ff-a718-1aff1e700dec.png)

**Comment by SandeepTalentelgia** [comment]
Closed, verified on live server.

**Comment by hassaanCD** [comment]
Working fine on production



![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/120023458/ab4638a3-8ede-4063-9dec-bf315be3c1cf)
