### ISSUE TITLE
As of Date Timezone issue - frontend

### ISSUE THREAD

**Issue by sajid315** [the-canonizer/canonizer-3.0-frontend#967]
Steps mentioned by Rupali, 

Go to the Date and Time settings.
Choose the region "United States"
Choose one of the three USA time zones: Mountain Time (USA & Canada), Central Time (USA & Canada), or Eastern Time (USA & Canada).
Go to https://canonizer3.canonizer.com/
Select any topic.
Make As of Date the earlier date than the topic's creation date.
Observe camp name on topic detail page
Actual Result : Camp name is blank

We can consider the loom screencast of this issue as well 
https://www.loom.com/share/465c53f7759f4c4c9f954e268fb92d94

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on live
