### ISSUE TITLE
Event Line: Event listing issues

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#968]
1. Events should be added at the top of list
Actual Result: Events are added at the end of list

![Image](https://user-images.githubusercontent.com/120023458/233051646-2595d6a4-1db4-4dda-bbef-fbeaa4276b24.png)

2. Event list should be scrollable
Actual Result: Event list is too large, it increases the page length

![Image](https://user-images.githubusercontent.com/120023458/233051961-d262a0e6-f17d-4b71-84fb-cf02808789f2.png)

**Comment by rupalichavan9860** [comment]
Working fine on staging
