### ISSUE TITLE
We have to replace the forward slash (/) with arrow (>) in all the breadcrumbs throughout the application

### ISSUE THREAD

**Issue by ks-rahul** [the-canonizer/canonizer-3.0-frontend#975]

**Comment by rupalichavan9860** [comment]
@BrentAllsop Do we also need to make this modification to email?

**Comment by BrentAllsop** [comment]
> @BrentAllsop Do we also need to make this modification to email?

Yes, I think this should be the standard, done everywhere.
Thanks for bringing this up.

**Comment by rupalichavan9860** [comment]
Created new ticket for emails https://github.com/the-canonizer/canonizer-3.0-frontend/issues/1040 so closing this

**Comment by rupalichavan9860** [comment]
Verified on live
