### ISSUE TITLE
Very first date of "Event Line" is not valid

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-frontend#996]
As shown in attached screenshot below

![Image](https://user-images.githubusercontent.com/120023458/235850531-6a724cd1-27ae-48bf-9ad4-852227c5bb49.png)

**Comment by shahab-ramzan** [comment]
@sunilspr7 this one issue was from frontend side we have fixed it and raised the PR. https://github.com/the-canonizer/canonizer-3.0-frontend/pull/998

**Comment by rupalichavan9860** [comment]
Working fine on staging
